### ISSUE TITLE
lighttpd.conf needs to load mod_setenv

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#994] opened 2018-01-16 18:46 UTC
Appliances that use lighttpd are logging errors.
````
lighttpd/error.log:2018-01-04 11:04:58: (server.c.1045) WARNING: unknown config-key: setenv.add-response-header (ignored) 
````
The problem seems to be that ssl.params.conf uses the setenv.add-response-header but it is ignored unless mod_setenv is loaded by the lighttpd.conf.  The change needs to be made in common so it applies to all appliances using lighttpd.

common/overlays/appengine-lighttpd/etc/lighttpd/lighttpd.conf
````
server.modules = (
    "mod_setenv",
    "mod_access",
    "mod_alias",
    "mod_compress",
    "mod_redirect",
    "mod_accesslog"
)
````

**Comment by JedMeister** [comment] 2018-01-16 20:31
Thanks @Dude4Linux ! Good catch!

**Comment by JedMeister** [comment] 2018-01-16 20:34
I think that's all the appliances that use Lighty...

**Comment by Dude4Linux** [comment] 2018-01-17 00:19
@JedMeister  Fortunately it only needs to fixed in one place, the common repository.  I stumbled across this while testing what I'm calling the TurnKey Portable Development Environment.  I'm grepping the logs of various appliances running in LXD containers looking for warnings and errors caused by running in an unprivileged container or by apparmor on the host.  This popped up in the Ansible appliance.  I'll be posting more about the PDE when I've completed the testing and documentation.

**Comment by Dude4Linux** [comment] 2018-01-17 00:28
@JedMeister BTW, what is the accepted protocol for filing an issue referencing one of the https://github.com/turnkeylinux repos?  I didn't clearly specify that the problem was in the 'common' repo.

**Comment by JedMeister** [comment] 2018-01-17 03:55
Great question... Actually, there isn't really any way. We have tags ('labels' in GH speak) for most (if not all) the software in repos as well as the individual appliances, but common is a bit of an outlier in that regard. So the short answer is that there isn't one! 

TBH, I'm not really sure what to do with that. You do raise a good point, but I'm not sure of the best "fix". 

I guess doing nothing is an option as we've got by until now without something explicit. In similar past situations, I've often prefixed the top post with specific info (such as "this will need to be fixed in common" or similar).

OTOH, perhaps we should do something with it and implement something? I'm open to thoughts and suggestions...

**Comment by JedMeister** [comment] 2018-01-18 07:16
I totally agree that the right way is to fix this particular bug is in common! No question or disagreement at all there.

I guess the way that I've always looked at it is that we tag the "thing" (package/appliance/etc) that has the bug/feature request, rather than necessarily where in the code the change needs to be made. Common being the exception; that will also match the repo (buildcode/package source/etc). So it's only in the case of when common needs to be tweaked that this scenario arises. 

That's probably the reason why we've never considered it to be a problem; most devs that work on TurnKey are aware of how things work and would always consider common whenever they work on an appliance (or at least they should).

IMO it at least somewhat makes sense to tag the item (package/appliance/etc) that has the bug. rather than which particular repo that it needs to be fixed in. My guess is that most bug reporters (and often myself too), may not be 100% sure where in the code the actual bug is (until someone actually has a look), just what appliance/etc it affects.

Historically, I've always just added a comment at the top of the OP noting when it requires changes in common (as soon as I know).

But like I say, your point is valid and "that's just the way we've always done it" isn't really a good enough reason to not change things if there is a better option. I guess that it may make it easier for newbs to contribute though and perhaps reduces the chances of someone just making the changes in each appliance.

Either way, if we know exactly what code should be patched, then it should be noted, in as much detail as possible (which I don't think is efficient to do via tags). I don't always do it, but I aim to make sure that all important info (from comments etc) is in the top post. I will often add info from comments if new info is discovered, unless of course someone is actively working on it. When that's the case, they should see the comment.

So if we were to add a new tag, what colour should we make it? I know that sounds somewhat trivial, but there is already something of a system to it. All the tags are currently colour coded as a "type". Orange tags are "products" (distributable source code of some sort) so common doesn't really fit with that (I currently use the orange tags, plus bug & feature via the GH API to track appliance update progress, so would rather not add a non-package/appliance orange tag). 

It doesn't really fit with any of the other tag "groups" either. E.g. buildtype is dark green/blue, yellow is to do with new appliances, blue is info about the bug report ("confirmed", "blocked", etc), red and green are bug and feature respectively. Now I'm looking purple does seem to be a bit of a grab bag, so perhaps purple would do? Or perhaps we could use a totally new colour?

**Comment by spaghettimaster** [comment] 2018-04-22 02:54
Done.
https://github.com/turnkeylinux/common/pull/121

**Closed** 2018-04-22 21:55 UTC
Labels: ansible, bug, domain-controller, lighttpd-php-fastcgi, mongodb, mysql, openldap, openvpn, postgresql
