### ISSUE TITLE
MySQL/MariaDB password can't include '@' &/or '#'

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1455] opened 2020-05-14 02:10 UTC
It's been reported in a [blog post comment](https://www.turnkeylinux.org/blog/v16.0-1#comment-48174) that if the Adminer MySQL/MariaDB password includes the characters `@` &/or `#` (the user couldn't recall which exactly, so we'll need to investigate further) then you can't log into Adminer.

The latest version of initihooks dialog supports blacklisting characters, so after testing, it should be pretty easy to block usage of the problematic character(s).

Also, it may be worth double checking on the commandline to see if it's inithooks itself, or Adminer (or MySQL/MariaDB) which is the problematic component. It may be possible to do something within inithooks to ensure that it works (rather than blacklist it)?

**Comment by OnGle** [comment] 2020-11-23 22:33
Unable to reproduce this issue setting password via inithook, or logging in using a password with any (or all) of these characters via cli or adminer.

I suspect this was fixed as part of https://github.com/turnkeylinux/tracker/issues/1414

Closing due to the fact it appears to already have been fixed

**Closed by OnGle** 2020-11-23 22:33 UTC
Labels: bug, inithooks, lamp, mysql
