### ISSUE TITLE
LDAP sync for customer user

### ISSUE THREAD

**Issue by TheStormbringer** [turnkeylinux/tracker#775] opened 2017-02-03 14:09 UTC
Hey guys, I've managed to enable the LDAP authentication for customer users successfully. Well... Almost.

The customers user can login using their AD-username and their AD-password - but I have to set a customer user with the exact username in the OTRS-Webinterface first.
So it appears that authentication is working, but my turnkey OTRS does not sync the users (they are all members of a specific AD-group) to OTRS.

Is there a way to enable all my AD-users to log into OTRS without adding them one by one to the OTRS customer user database manually?

Kind regards

**Comment by JedMeister** [comment] 2017-02-07 07:37
Hi,

This is actually our Issue tracker. I.e. for reporting bugs and feature requests. Your problem sounds more like something you need support with, which is probably a better candidate for our [forums](https://www.turnkeylinux.org/forum/) (that is unless there is actually a bug causing your issue). 

As for your question; I'm almost sure that there is a way, but TBH I have no idea. LDAP is something that I have only a very basic grasp of. 

I recall a few years ago, I used a PHP module that allowed a remote LDAP DB to provide authentication to a web app I was working on. I never really understood how it worked, but it did (it was running within a LAN though - not sure if it would be secure running online?) I'm assuming that there is probably some similar Perl module that OTRS could leverage to provide authentication? 

Alternatively, perhaps there is some way to have a cron job which updates the local DB with LDAP users?

Anyway, sorry I'm not much help to you. I'm going to close this now. Please feel free to reopen if you discover that it actually is caused by a bug. Also please feel free to open a new thread on the forums.

**Closed by JedMeister** 2017-02-07 07:37 UTC
