### ISSUE TITLE
Lapp not successfully restarting at Install

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#345] opened 2015-05-11 08:07 UTC
First Happened on Odoo...Now testng PURE VANILLA LAPP

 After Grub Setup.  Chose, "ok to restart".
Console drops.  System does not restart still after 10 min.  Will give reset command.

Partially rleated to VMWare the Dialog about Ejecting the CD  (which was hidden).  Not something that came up before that I recall.  Still needed to issue a reset command to get system to stop.  

Says:  "A stop job is running for di-live".  Not restarting however.
This is a Pure LAPP appliance made from TKLDEV Jessie RC1

**Comment by l-arnold** [comment] 2015-05-11 08:21
UPDATE:  Lapp not migrating Apache Successfully.
thought the issue was in Odoo install but repeated in LAPP (pure)

For Web get: Debian Logo Apache2 Debian Default Page
...  but now can't log in to root either.  (late)  will try the install again in AM

**Comment by JedMeister** [comment] 2015-05-12 13:16
Thanks for reporting but this is a known issue.

Closing as this is a duplicate of #339

**Closed by JedMeister** 2015-05-12 13:16 UTC
