### ISSUE TITLE
Turnkey Fileserver webmin/web shell fails with external storage attached

### ISSUE THREAD

**Issue by Silent-Hunter** [turnkeylinux/tracker#1353] opened 2019-08-23 20:03 UTC
I installed the latest ISO downloaded from the Turnkey website in a Proxmox VM, and it worked, I was able to access webmin and the web shell. Then I changed to a static IP, shut down the VM, and added a 4TB external drive. On booting back up, the webmin and shell give a connection refused error. I tried it again, but added the external drive before installing Turnkey, and it did the same thing.

It's Proxmox Virtual Environment 6.0-4 and Turnkey Fileserver 15.0.

**Comment by JedMeister** [comment] 2019-08-26 00:39
Hi there.

I suspect that this is something that has gone wrong, specific to your setup, rather than a TurnKey bug. As a general rule, we prefer to provide support via our [forums](https://www.turnkeylinux.org/forum) and try to reserve GitHub "issues" for bugs and/or feature requests (i.e. action required on our part). I'll close this for now (in anticipation that it's something wrong with your specific setup, rather than a TurnKey bug). But seeing as you've already posted here, I'll give you few pointers:

As it's both Webmin and Webshell that aren't working, my guess is that the Stunnel service is not running, or has failed (both Webmin and Webshell are running behind Stunnel). So I'd recommend checking (the service is actually named `stunnel4`). Do that like this:

```systemctl status stunnel4```

For completeness, you can also check Webmin and Webshell services too (Webshell is also known as `shellinabox`):

```
systemctl status webmin
systemctl status shellinabox
```

The system log may also give you some indication of why things aren't working. You can access that via the `journalctl` command:

```journalctl```

To just view info from the journal about a specific service, use the `-u` switch. E.g.:

```journalctl -u stunnel4```

Hopefully that might give some insight into what the actual cause of the issue is.

**Closed by JedMeister** 2019-08-26 00:39 UTC

**Comment by Silent-Hunter** [comment] 2019-08-26 02:29
Yes, it was my fault. I had three VMs running already, one with 8GB of RAM allocated, and two others with 3GB each. Then I added Turnkey fileserver and gave it 3GB. The machine only has 16GB of RAM in total. So I overprovisioned it by a whole gigabyte. Sorry for bothering you!

**Comment by JedMeister** [comment] 2019-08-26 03:10
All good. Thanks for confirming that there isn't a bug. :smile:
