### ISSUE TITLE
TKLDev sandbox mode does not work

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#616] opened 2016-04-22 10:06 UTC
**[update from Jeremy]** - for now, we'll probably just leave the sandbox out, but we need to update the docs to reflect the fact that that's no longer a thing...

----

Reading the Hello World [manual](https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/helloworld.rst) and trying it on the side, I have found that when the sandbox filesystem is changed and make called, it does not take 11 seconds, but begins from scratch, and fails with
`error: root.sandbox is dirty with manual changes. To continue: deck -D build/root.sandbox`
When I do that, the changes are thrown away. And the next make starts from scratch again.

And I'm afraid that the second part ending with `make root-patched` also does not take 12 s, but builds it from scratch.
##

**Comment by JedMeister** [comment] 2016-04-22 11:13
I'll have a quick look and see what I can see...

**Comment by JedMeister** [comment] 2016-04-25 06:16
I wonder if this behaviour is a regression introduced when fixing #530? Or whether it is another altogether separate bug?

**Comment by qrntz** [comment] 2016-05-13 09:22
It is a regression indeed… the problem with reversing the change however is that the #530 file spillage returns. I'm trying to work around it.

**Comment by JedMeister** [comment] 2016-08-30 01:37
For now, it seems like the best path forward would be to scrap the `root.sandbox` altogether. This requires us to update the docs to no longer include reference to it in the docs.

**Comment by DocCyblade** [comment] 2016-10-08 06:00
So, when you say the sandbox is broke, does this mean you can not build to sandbox (skip the ISO part) and chroot into the sandbox and play around? It's been while since I was playing around with TKLDev (almost a year) and I remember doing that so I could quickly test a config change, then do a fuser command to kill all the processes in the sandbox, then remove the sandbox deck then build the ISO if everything worked in the chroot. Does that still work or do I need to build ISO every time?

**Comment by DocCyblade** [comment] 2016-10-09 07:04
This bug is really bugging me! It's put a wrench in my dev work. Where I used to be able to throw away the root.patch and start over, you have to rebuild it every time!

I have been pouring over the source for the make files, deck and other things. I think I may have found the issue, and I don't think it's related to #530. I'll post more when I think I have it narrowed down

**Comment by DocCyblade** [comment] 2016-10-09 08:20
Well, ok I can CONFIRM that #530 introduced this issue. Squash one bug, it polymorphs into another!

See my commands below, I basically reverted the deck.py back to the last commit, and it works like it should.

For clarification, does the old bug only show it's head when you make ISO? 

```
root@tkldev products/core# ~/switch_deck_current.sh 

Switch deck.py to [master]
'/usr/lib/deck/pylib/deck.py.current' -> '/usr/lib/deck/pylib/deck.py'
-rw-r--r-- 1 root root 9936 Oct  9 07:50 /usr/lib/deck/pylib/deck.py
deck.py state is now that of [master]

root@tkldev products/core# make clean

root@tkldev products/core# make root.sandbox

... (builds) ...

touch build/stamps/root.patched
deck build/root.patched build/root.sandbox
touch build/stamps/root.sandbox

root@tkldev products/core# rm build/stamps/root.sandbox 
root@tkldev products/core# make root.sandbox
deck -D build/bootstrap
deck -D build/root.build
deck /turnkey/fab/bootstraps/jessie build/bootstrap
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/apt build/bootstrap;

... (starts the whole build) ...

root@tkldev products/core# make clean
deck -D build/root.sandbox
deck -D build/root.patched
deck -D build/root.build
deck -D build/bootstrap
rm -rf build/root.spec build/cdroot build/product.iso build/log build/stamps

root@tkldev products/core# ~/switch_deck_prev.sh 

Switch deck.py to commit [53a3280]
'/usr/lib/deck/pylib/deck.py.prev' -> '/usr/lib/deck/pylib/deck.py'
-rw-r--r-- 1 root root 9942 Oct  9 08:05 /usr/lib/deck/pylib/deck.py
deck.py state is not that of commit [53a3280]

root@tkldev products/core# make clean
deck -D build/root.sandbox
deck -D build/root.patched
deck -D build/root.build
deck -D build/bootstrap
rm -rf build/root.spec build/cdroot build/product.iso build/log build/stamps
root@tkldev products/core# 
root@tkldev products/core# make root.sandbox

... (builds) ...

touch build/stamps/root.patched
deck build/root.patched build/root.sandbox
touch build/stamps/root.sandbox
root@tkldev products/core# 

root@tkldev products/core# rm build/stamps/root.sandbox 
root@tkldev products/core# make root.sandbox 
deck -D build/root.sandbox
deck build/root.patched build/root.sandbox
touch build/stamps/root.sandbox
root@tkldev products/core# 
```

**Comment by JedMeister** [comment] 2016-10-09 21:26
Sorry I haven't got to you sooner Ken... From memory, yes, the old bug only becomes noticeable after you have built to ISO.

FWIW I never used the root.sandbox anyway (I like the idea but you can use root.patched itself to achieve a similar ends).

Personally the way I usually do it is to force the build to fail by adding `exit 1` to the conf script. Then build to root.patched:

````
make root.patched
````

You can then play around in there (just like it was the sandbox):

````
fab-chroot build/root.patched
````

When you are done playing and want to retest building your code you just rebuild to root.patched: `make root.patched`. Because the last build failed it will rerun cleanly. Make sure you copy out your work (i.e. copy commands to your conf script(s) and copy out files you plan to overlay) before you rebuild as it will be destroyed.

When you are ready to build the ISO just remove the `exit 1` from the conf script. 

If at some point you build to root.patched cleanly but you want to rebuild root.patched again (without rebuilding from scratch) you just need to manually undeck root.patched and remove the stamp. You may need to use `fuser` to stop processes which are running in the chroot. From memory it goes something like this:

````
fuser -k build/root.patched
deck -D build/root.patched
rm stamps/root.patched
make root.patched
````

I may have got some of those commands wrong as it's been a while for me too, but that should get you going in the right direction...

**Comment by lirazsiri** [comment] 2017-01-06 12:09
I'm looking into fixes as this vastly increases the length of the development cycle, which is not a good thing. Starting from scratch each time is a major drag. There's an easy workaround that doesn't involve reverting the Anton's file spillage fix to deck. If I can't fix deck directly I'll commit a fix to that.

**Comment by lirazsiri** [comment] 2017-01-06 13:57
I haven't found an easy fix yet for the deck regression. In the meantime, I'll document the test case for reproducing this in a way that also tests whether the file spillage issue is resolved. If orig/ is newer than orig.timestamp and we have a build process that assumes the orig/ timestamp is fixed that is going to trigger a target rebuild:
``
mkdir -p orig/
touch orig/deletethis
touch orig/file

deck orig/ 0/

# reproduce bug
touch orig.stamp; deck -D 2 || true && deck -D 1 || true && deck 0/ 1 && rm 1/deletethis && deck 1/ 2/ && [ -f 2/deletethis ] && echo "BUG: 2/deletethis exists" || echo "OK: ! 2/deletethis " && ls -la --full-time |grep orig

OK: ! 2/deletethis 
drwxr-xr-x 3 root  root  4096 2017-01-06 15:50:22.069703752 +0200 orig
-rw-r--r-- 1 root  root     0 2017-01-06 15:50:21.397710827 +0200 orig.stamp

**Comment by lirazsiri** [comment] 2017-01-06 14:19
I committed a simple workaround which can easily be applied by hand to existing versions of TKLDev:

https://github.com/turnkeylinux/fab/commit/852238033637e6b1034332938f4c6d7aa0c00ef3

**Closed by lirazsiri** 2017-01-06 14:19 UTC
Labels: bug, documentation, tkldev
