### ISSUE TITLE
New appliance: Foodsoft

### ISSUE THREAD

**Issue by wvengen** [turnkeylinux/tracker#216] opened 2014-06-21 19:22 UTC
Foodsoft is web-based software for managing non-profit food coops (product catalog, ordering, accounting, job scheduling).

* Repository: https://github.com/foodcoops/turnkeylinux-foodsoft
* Tracker: https://github.com/turnkeylinux/tracker/wiki/Foodsoft
* Upstream: https://github.com/foodcoops/foodsoft
* by @wvengen (also maintainer of upstream)

This Rails appliance is a little unusual in the sense that two versions of the app are shipped, with a choice at firstboot. (In the future I might perhaps add an option to switch between the two at a later time.)

One thing that's a little unclear to me about tkbam: do logfiles need to be filtered out?

(a new upstream version will be released the 25th of June, I'm submitting it now so that, perhaps, the TurnKey Linux appliance can be mentioned in the release announcement; let's see :) )

**Comment by JedMeister** [comment] 2015-05-10 02:16
@wvengen As I just posted on another thread; (it's verbatim cut & paste sorry; but equally applies to you so hope that you're not offended).:

Sorry it has taken us so long so far... TBH it is embarrassing :frowning: And I imagine that having to wait this long to see code you wrote actually make it to a release must be frustrating! I imagine that it certainly wouldn't be very motivating...

Anyway, we are (finally) working on a new release (v14.0) that we won't be getting sidetracked from! (I promise!)

I was just going to get someone else to update your code for the v14.0 release (with the latest version of Laravel) but thought perhaps I should check with you first. Are you at all interested in updating your appliance or would you like me to get someone else to do it?

**Comment by JedMeister** [comment] 2015-05-10 02:17
PS I will be getting common Rails stuff updated fairly soon and I can post back when that's happened if you want? Or just get someone else to work on it...?

**Comment by wvengen** [comment] 2015-05-11 21:41
Thanks, that great news! Great to read what's improved and why in the release notes. And no problem for the wait - there's always more to do than is possible, and one needs to make choices.

I'll be happy to look at the appliance for v14.0. It'd be useful if there's a way to obtain a new tkldev instance (since building it from v13.0 [may not be](http://www.turnkeylinux.org/forum/support/20150508/tkldev-make-failing-core-and-others-no-changes) so straightforward - trying now).

I suppose the new ruby version will be [2.1.5](https://packages.debian.org/jessie/ruby)? There are some gems requiring ruby 2+ nowadays. (And the Ruby Enterprise notes and customizations can be removed, I guess.) Looking forward to any tkl-rails changes!

**Comment by JedMeister** [comment] 2015-05-12 02:09
Awesome! And thanks for your patient and understanding attitude! :smile: 

Yes there is a new v14.0RC1 TKLDev iso ([263MB 64bit ISO](http://www.turnkeylinux.org/download?file=turnkey-tkldev-14.0rc1-jessie-amd64.iso)). I haven't yet publicly announced it but some people already know about it so please feel free to have a look...

TBH though I expect that the Rails appliance is a little broken ATM (it hasn't been touched yet...). And yes it will use the Debian Jessie default version which will hopefully make installing Foodsoft (and other apps) a little neater...

Regardless please feel free to either have a play and note (and fix if you want/can) any issues (with any of the appliances, although ATM you'll need to build them yourself with TKLDev). As I said though hopefully someone will be on to Rails within the next day or so...

**Comment by wvengen** [comment] 2015-05-12 13:08
Thanks!
@JedMeister building the Passenger Apache2 module now requires installing `libssl-dev`, which was missing in common's `plan/turnkey/rails`. May be helpful when looking at the rails appliance.
Then probably also `a2dissite default` -> `a2dissite 000-default` in `conf/rails` (among other appliances) - but I'm testing that right now.

**Comment by JedMeister** [comment] 2015-05-13 00:16
Cheers on that. I just commented on your pull request and mentioned the guy that I'll get to have a deeper look at it. Will try to keep you posted...

**Comment by wvengen** [comment] 2015-06-27 09:39
The only thing left is that mysql doesn't start automatically, for the rest it passes basic testing. Would anyone like to check if this is an issue with my setup, or a more general problem? I'm unsure about that since https://github.com/turnkeylinux/common/pull/18#issuecomment-101998828.

**Comment by JedMeister** [comment] 2015-06-29 01:34
Building now...

Will post back.

**Comment by JedMeister** [comment] 2015-06-29 02:10
My build failed. It was definitely MySQL but not an issue with it starting...

Last lines of make prior to failure:
````
+++ ls -d /var/lib/gems/2.1.0/gems/passenger-5.0.11
++ echo /var/lib/gems/2.1.0/gems/passenger-5.0.11
+ PASSENGER_ROOT=/var/lib/gems/2.1.0/gems/passenger-5.0.11
+ sed -i 's|PASSENGER_ROOT|/var/lib/gems/2.1.0/gems/passenger-5.0.11|g' /etc/apache2/mods-available/passenger.conf /etc/apache2/mods-available/passenger.load
+ MYSQL_BATCH='mysql --user=root --password= --batch'
+ MYSQL_ADMIN='mysqladmin --user=root --password='
+ /etc/init.d/mysql start
df: Warning: cannot read table of mounted file systems: No such file or directory
[ ok ] Starting MySQL database server: mysqld . ..
[info] Checking for tables which need an upgrade, are corrupt or were 
not closed cleanly..
+ for DB_ENV in test development production
+ DB_NAME=turnkeylinux-foodsoft_test
+ mysqladmin --user=root --password= create turnkeylinux-foodsoft_test --default-character-set=utf8
+ mysql --user=root --password= --batch --execute 'grant all privileges on turnkeylinux-foodsoft_test.* to turnkeylinux-foodsoft@localhost identified by '\''364e9f006832f3f7875dc7b0b203deb9'\''; flush privileges;'
ERROR 1046 (3D000) at line 1: No database selected
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
make: *** [build/stamps/root.patched] Error 1

````

**Comment by JedMeister** [comment] 2015-06-29 02:36
Ok I investigated this a little more and it seems that the issue is your DB name (turnkeylinux-foodsoft_test). Apparently as a general rule it is better to avoid DB names that include a dash in MySQL. If you do use a DB name with a dash then you need to surround it with backticks everytime you mention it...

Probably better to just change the DB name IMO.

**Comment by wvengen** [comment] 2015-06-29 15:48
Thanks, I'll fix it!

**Comment by wvengen** [comment] 2015-06-29 17:16
This happens because the repository is called `turnkeylinux-foodsoft`, but in TKLDev it should be called `foodsoft` (which will happen, I presume, when it is added as an official repository). When you rename the directory to `foodsoft`, this build would probably succeed. Then the database names are without a hyphen, and I'm curious if MySQL starts for you at boot. No clue yet.

(`DB_NAME="${HOSTNAME}_${ENV}"`, and `HOSTNAME=$(shell basename $(shell pwd))`)

**Comment by wvengen** [comment] 2015-06-29 17:23
I have a clue, it's probably caused by the inithooks script.

**Comment by JedMeister** [comment] 2015-06-30 04:37
Ok I renamed the dir I had it in to 'foodsoft' and remade it. Completed a treat. I then installed the ISO `foodsoft/build/product.iso`) into a KVM VM. I installed it and ran through the inithooks and it just works. Works a treat that is! I didn't need to do anything with MySQL (it started all of it's own accord). FYI I am using the current HEAD of both common and your repo... Great work all round IMO! :+1: 

The inithooks all appear to work too (at least the one that sets the password does). I didn't dig into it very deep but i did log into FoodSoft successfully (using the password I set when the inithook ran at firstboot).

Some feedback:
Personally I'd make the default email "admin@example.com"; not because it's in any way superior just that's what the others do...

Also what is the difference with "Adam's branch"? Is his branch really popular? Is swapping to that something that many people would want to do? Or even know about (or need to find out about)? Could changing to it be easily documented instead? Or done afterwards with some sort of helper script instead? 

As a FoodSoft newb whether or not I want Adam's branch is not a question I know the answer too (without research) and TBH I'd rather not have the choice (just give me the "best" one! :stuck_out_tongue_winking_eye: ) However I'm guessing that other's (FoodSoft Pros that is) may feel differently...

[update] I have just done a bit of reading and it seems to me that new users would be best advised to use the upstream version and that it is probably more current users of Adam's branch that may wish to continue down that path...?! 

Regardless, my opinion (0.02:dollar:)  is to decide who your primary market for the TurnKey appliance is and which version they would most likely want. Then install that version by default and document and/or script swapping to the other... Unfortunately we don't yet have it, but whether or not the end user has the choice of different branches would be nicely solved by #369....

**Comment by wvengen** [comment] 2015-07-01 22:26
Thank you for testing, and providing valuable feedback!
I've changed the email address, good to have it similar to others.

There is currently no way to change the branch afterwards - that's why I put it here. The users I know that want to use a TKL version would like to use the adam branch, and are not technically proficient enough to login to the system and change it that way.

I'd opt for moving branch choosing to a confconsole menu when that is possible in TKL.

**Comment by JedMeister** [comment] 2015-07-02 00:36
Ok well with the new info you've given then it sounds like that question really needs to stay (at least until we have the "advanced" inithooks menu). I don't recall the text now but if it fits and doesn't look to busy perhaps you can add something like "if you don't know the answer to this question you want default branch" or something similar...? I'll leave that to you.

Regardless great work and I'm looking forward to finally adding your appliance to the library (after how long...?!?) :smile:

**Comment by JedMeister** [comment] 2015-08-31 03:42
merged into tkl library: https://github.com/turnkeylinux-apps/foodsoft

**Closed by JedMeister** 2015-08-31 03:43 UTC
Labels: foodsoft, new-appliance, ready-to-go

**Comment by wvengen** [comment] 2015-08-31 07:14
Nice :+1:

**Comment by JedMeister** [comment] 2015-09-07 02:56
Hey @wvengen - Sorry about this but I have been speaking with Alon and we need to pick one of the versions to use by default. Otherwise the appliance won't be supported by the Hub. The Hub supports a range of "standard" inithooks and Alon is not willing to adjust those at this point. This means that your question re version will not be supported in the Hub.

At the very least we need to make it so that it can be preset to a specific version if launched headlessly (e.g. via the Hub). Preferably it would just use one and then the other could be swapped in later (with a helper script perhaps...?). Just having a look over the inithook and it seems to me that pulling the version bit out and making it a standalone helper script seems possible?

Thoughts? 

We need to do something ASAP and if nothing else happens then we may end up just having to hardcode a default to one version or the other... Apologies on the pressure (it's just we're trying to build images and do final touches prior to release).

**Comment by wvengen** [comment] 2015-09-07 12:06
I can understand, will have a look asap.

**Comment by alonswartz** [comment] 2015-09-09 08:30
Just to be clear, this is not just for Hub based deployments, but for all headless deployments [1]. I'm currently working on a fix, will update the issue as soon as I have something...

[1] http://www.turnkeylinux.org/docs/builds

**Comment by alonswartz** [comment] 2015-09-09 09:01
@wvengen just to verify, the default variant should be ``foodsoft-standard``, right?

ref: https://github.com/turnkeylinux-apps/foodsoft/commit/51d655ac3ac7dd475c05a8ef40646a0a33df7ac4

**Comment by wvengen** [comment] 2015-09-09 09:12
Yes, `foodsoft-standard` is the default. Great plan to have a default value in any case.

If that's enough, great. If you'd rather not have the question asked at all, or not even ship the alternate version, I can look into having a script to change that afterwards (though the latter would require some time to write and test).
