### ISSUE TITLE
[Jessie] Inithooks start before booting finishes

### ISSUE THREAD

**Issue by SiKing** [turnkeylinux/tracker#356] opened 2015-05-15 17:43 UTC
I grabbed TKLDev 14.0RC1 and went through the tutorial to build the core product.iso. When I launch that in my VM, at the screen that asks to enter a new root password, the prompt gets messed up. See attachment. This happens consistently for other products as well.
![untitled](https://cloud.githubusercontent.com/assets/5496738/7658469/4e314ea2-faef-11e4-8ca2-8a800487da42.png)

**Comment by SiKing** [comment] 2015-05-15 18:08
Should have mentioned: There is nothing wrong with the _functionality_, the screen correctly accepts the password. This is just a display problem.

**Comment by JedMeister** [comment] 2015-05-16 06:37
Thanks for reporting. I'm 99% sure that its a systemd thing...

**Comment by JedMeister** [comment] 2015-05-16 06:56
This is caused by the same issue as #338

**Comment by JedMeister** [comment] 2015-05-21 01:06
I just renamed this to better reflect what the problem is. Hope you don't mind @SiKing

**Comment by JedMeister** [comment] 2015-11-30 03:02
Limitation of systemd; labelled as "won't fix" and closing for now.

**Closed by JedMeister** 2015-11-30 03:02 UTC
Labels: bug, core, inithooks, won't fix
