### ISSUE TITLE
TKL Setup - Manual LVM setup errors

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#1183] opened 2018-08-27 14:04 UTC
The scripts breaks when selecting Manual, select Configure the Logical Volume Manager then select Display Config details, script breaks and you have broken menu selection. 

Maybe issue with the commands being submitted by the python script.

**Comment by DocCyblade** [comment] 2018-08-27 14:04
I am at work right now and can’t get a screen shot. (Yeah installing a new TKL v15 server!

**Comment by DocCyblade** [comment] 2018-08-27 14:06
Should say this is on VMWare ESX platform

**Comment by JedMeister** [comment] 2018-08-27 22:27
Hmm that sucks! It's been a while since I tested the installer, although I thought that we had it all working great?! Obviously not! I wonder if this was a regression introduced by the latest fix we applied?

I'll try to reproduce shortly and post any specifics that I find. Cheers for reporting @DocCyblade

**Comment by JedMeister** [comment] 2018-08-28 00:42
Ok, I was just about to write that I couldn't reproduce your issue (as I just successfully installed using manual partitioning with LVM).

However, I missed some screenshots and tried again (paying closer attention to your notes). Doing that I did reproduce the issue!

As you noted, the issue is triggered by selecting "Display Config details" within the LVM config menu. If you don't select that option, then it is possible to complete the setup with manual partitioning and LVM.

Here's the relevant screenshots:

![screenshot from 2018-08-28 10-22-19](https://user-images.githubusercontent.com/818633/44694076-e3579780-aaae-11e8-99d4-44f07d6c9b21.png)

![screenshot from 2018-08-28 10-22-31](https://user-images.githubusercontent.com/818633/44694080-e6eb1e80-aaae-11e8-8d15-7469b0dd1841.png)

**Comment by JedMeister** [comment] 2020-01-12 22:16
We should double check whether this still applies (I've done some major refactoring/rewriting of `di-live` for v16.0).

**Comment by JedMeister** [comment] 2020-04-02 22:18
TBH, I'm not sure if this is still an issue in v16.0. We'll need to test and see.

I had hoped to confirm (or not) but I really need to push ahead with v16.0, so repinning this to v16.1.

**Comment by JedMeister** [comment] 2021-02-02 05:19
TBH, I'm not sure whether this still applies (I don't think it does, but it might...). Regardless, I'm going to close this one for now. If it's still an issue (or there are similar issues) we can opne a new up to date issue.

**Closed by JedMeister** 2021-02-02 05:19 UTC
Labels: bug, core, di-live
