### ISSUE TITLE
New ConfConsole Testing: Error in Region Config

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#746] opened 2016-12-06 03:50 UTC
@qrntz 

Getting an error on each of the three menu options. I think there is system variable I am missing. I posted a new issue as this does not fit any existing issue I know of.

<img width="504" alt="screen shot 2016-12-05 at 10 47 19 pm" src="https://cloud.githubusercontent.com/assets/9731860/20912392/fff02b72-bb3c-11e6-8cd3-6cc0e975968c.png">

**Comment by qrntz** [comment] 2016-12-12 04:32
https://github.com/turnkeylinux/confconsole/commit/f7de5ddb08ccd509cc5f021ebf5f894312c2617f broke it by making `pluginManager` an instance variable.

Local state is good, but I don't think in this particular case it's a good idea. `TurnkeyConsole` is inherently interactive. It doesn't make sense to initialize a Dialog instance in the constructor then. However that is where the `pluginManager` is now initialized (which also means no possibility to check for a plugin existing before a `TurnkeyConsole` is instantiated unless the respective methods are refactored out of the class).

@OnGle?

**Comment by JedMeister** [comment] 2016-12-12 23:37
Thanks for the report @DocCyblade and thanks for the followup @qrntz.

@OnGle is a bit busy ATM, but I'll get him to look into this as soon as he's able (hopefully this week?).

**Comment by OnGle** [comment] 2016-12-20 01:19
Sorry for the long period of being dark on the azure stuff. So first of all my mind's diverged a bit from the confconsole stuff so I'll have to have a look at the code to properly understand what you're saying. I think I got a bit overzealous in the plugin system's creation, making a lot of decisions that probably should of been better thought out.

Also, what's the status of this, I'm happy to fix the bug if I'm not stepping on anyones toes? :)

**Comment by OnGle** [comment] 2016-12-20 01:49
So after having a bit of a look, first of all I've got to apologize for the lack of granularity in my commits, second of all. I'm still a little unclear as to the cause of this issue, I can't for the life of me find where interactive was being set, or if it was being set at all.

While I don't doubt you, I'm struggling to see the correlation between the lack of "interactive" in plugins and pluginManager being set as an instance variable. Any chance you could share some context @qrntz?

**Comment by qrntz** [comment] 2017-01-15 17:34
Sorry, took me a (long) while.

@OnGle, basically, I implemented interactive by adding it to the globals dict to be passed to `PluginManager` (and made available to plugin code). This method no longer works because `TurnkeyConsole` [initializes its own PluginManager](https://github.com/turnkeylinux/confconsole/commit/f7de5ddb08ccd509cc5f021ebf5f894312c2617f?diff=unified#diff-e4f0afceac2ccbebaea20b98b5dcdcffR153) as an instance variable and then uses `self.pluginManager` everywhere. Passing a `TurnkeyConsole` instance as `tc` to the other `PluginManager` (initialized at the top level) doesn't do much because that PM instance is not the one that invokes the plugins.

Compare https://github.com/turnkeylinux/confconsole/commit/9ac910bd51bc561878a129265cc0c18e3539ca49 and https://github.com/turnkeylinux/confconsole/commit/f7de5ddb08ccd509cc5f021ebf5f894312c2617f — the `PluginManager` that is actually running the plugins is [this one](https://github.com/turnkeylinux/confconsole/commit/9ac910bd51bc561878a129265cc0c18e3539ca49#diff-e4f0afceac2ccbebaea20b98b5dcdcffR605) originally, but [that one](https://github.com/turnkeylinux/confconsole/commit/f7de5ddb08ccd509cc5f021ebf5f894312c2617f?diff=unified#diff-e4f0afceac2ccbebaea20b98b5dcdcffR153) in the merged code. It does not set `interactive` and there is no means to. Meanwhile, the instance that does is not used by `TurnkeyConsole`.

My original comment refers also to the fact that if we are (as now) to initialize `PluginManager` inside `TurnkeyConsole`, we are setting up the interactive environment before actually deciding if the plugins we have are to be run interactively or not. Adding an interactivity check to `TurnkeyConsole` does not make much sense to me, after all it is just an abstraction for an interactive environment; why initialize it if we are not interactive. Otherwise we have to create a `PluginManager` prior to deciding whether to instantiate a `TurnkeyConsole` (as in the original commit).

**Comment by OnGle** [comment] 2017-01-17 00:04
First of all I really appreciate you giving me all that info mate :)

Now, I see the two plugin manager instances, the global pm and the turnkey console instance variable, however in between the 2 commits you've noted I don't see any difference too how they're setup, both commits error for me giving "global name interactive not defined".

As far as the plugin manager instance, I agree absolutely, the turnkey console is an abstraction of the interactive part and it was poor judgment to create an instance and optionally make interactive AFTER it already must be interactive. 

I'm gonna have a bit of a hack around with this. I feel like there should be no need to have the plugin manager instance created within turnkey console, perhaps we could create it separately and pass it too the turnkey console which would update the globals with interactive?

**Comment by JedMeister** [comment] 2017-01-27 09:26
To make things easier for everyone and to speed up the development cycle I have created a "dev-testing" repo (hosted on AWS S3). So now rather than needing Alon to update the packages in the TurnKey "jessie-testing" repo, I can just rebuild and upload.

It's now up and running. I haven't tested it thoroughly, but it appears to be working as it should. It currently has a new version of confconsole, as well as a number of other bits and pieces. I intend to upload newer Webmin packages there really soon too.

Instructions on how to set it up and use it are on the home page:
https://s3.amazonaws.com/tkl-dev-test/index.html

**Comment by JedMeister** [comment] 2017-01-31 22:01
@DocCyblade:

This particular issue (and some others) should now be resolved in the latest test package - which I just uploaded (as noted [here](https://github.com/turnkeylinux/confconsole/pull/8#issuecomment-276503627)).

When you get a chance, please feel free to <s>break</s> test it! :smile: If you can confirm this issue is resolved, please close it. Please open new issues if/as you find them. It would be helpful if you could include the output of `apt-cache policy confconsole` so we can be sure of the version you are testing.

**Comment by DocCyblade** [comment] 2017-02-01 01:45
@JedMeister sounds good. I'll have to find your post regarding the test repo.

**Comment by JedMeister** [comment] 2017-02-01 02:01
Testing repo (and set up instructions) and here: http://tkl-dev-test.s3-website-us-east-1.amazonaws.com/

**Comment by DocCyblade** [comment] 2017-02-01 02:02
Perfect! After I commit some work on adminer I'll have a go with this tonight

**Comment by JedMeister** [comment] 2017-02-01 02:04
I double checked the set up instructions for the testing repo yesterday and confirmed they work (after I fixed them that is...!). As per always though, please give feedback if you think they could be improved for clarity etc.

**Comment by JedMeister** [comment] 2017-02-01 04:28
I'm going to close this as I don't think it's an issue anymore. If I'm wrong, please feel free to reopen.

**Closed by JedMeister** 2017-02-01 04:28 UTC
Labels: bug, confconsole

**Comment by DocCyblade** [comment] 2017-02-02 03:30
Confirming this is good
