### ISSUE TITLE
https://releases.turnkeylinux.org/pve/ is down

### ISSUE THREAD

**Issue by ftpman** [turnkeylinux/tracker#1408] opened 2020-01-27 19:39 UTC
I can't update turnkey templates on proxmox because update links is down:

https://releases.turnkeylinux.org/pve/aplinfo.dat
https://releases.turnkeylinux.org/pve/aplinfo.dat.asc
https://releases.turnkeylinux.org/pve/aplinfo.dat.gz

Cloudflare respond with a 521 error.

#987

**Comment by JedMeister** [comment] 2020-01-27 21:43
Sorry about that. I strongly suspect that it's related to #1407

**Comment by JedMeister** [comment] 2020-01-28 09:12
Please see https://github.com/turnkeylinux/tracker/issues/1407#issuecomment-579148820

**Comment by JedMeister** [comment] 2020-01-29 22:03
Closing now. It's backup and we're pretty sure that we've addressed the cause of the issue.

**Closed by JedMeister** 2020-01-29 22:03 UTC
Labels: bug
