### ISSUE TITLE
Observium API responses

### ISSUE THREAD

**Issue by honeyfairy** [turnkeylinux/tracker#1373] opened 2019-10-31 16:49 UTC
Note: I could not find out exactly where to ask this but hopefully someone will respond here:

Issue:
The responses I get via API for graphing does not make sense. I followed the manual. But the responses I get seem to just increment .. ?..
```

**user@testserver:~$ curl -u test:test http://10.0.0.7/graph.php?type=port_bits&to=now&id=4&from=-1h&height=300&width=1152
[16] 8030
[17] 8031
[18] 8032
[19] 8033
[20] 8034
[11]   Done                    curl -u test:test http://10.0.0.7/graph.php?type=port_bits
[12]   Done                    to=now
[15]   Done                    height=300
[18]   Done                    id=4
[19]-  Done                    from=-1h
user@testserver:~$ curl -u test:test http://10.0.0.7/graph.php?type=port_bits&to=now&id=4&from=-1h&height=300&width=1152
[21] 8041
[22] 8042
[23] 8043
[24] 8044
[25] 8045
[16]   Done                    curl -u test:test http://10.0.0.7/graph.php?type=port_bits
[17]   Done                    to=now
[20]   Done                    height=300
[22]   Done                    to=now
[23]   Done                    id=4
user@testserver:~$ curl -u test:test http://10.0.0.7/graph.php?type=port_bits&to=now&id=4&from=-1h&height=300&width=1152
[26] 8046
[27] 8047
[28] 8048
[29] 8049
[30] 8050
[21]   Done                    curl -u test:test http://10.0.0.7/graph.php?type=port_bits
[24]   Done                    from=-1h
[25]   Done                    height=300
[27]   Done                    to=now
[28]   Done                    id=4
user@testserver:~$** 

```

Here I have posted a snippet. I am testing from another server on the same LAN.

The current speed of the traffic flowing is supposed to be reported, right? 

That port is running at around 150mb, but this is not shown in the response.

**Comment by JedMeister** [comment] 2019-11-01 02:03
Hi @honeyfairy - FWIW we aim to reserve our "issue tracker" explicitly for 'bugs' and 'feature requests' and this doesn't seem to be either of those. Although I guess it could potentially be either, once you've worked out what the problem is! :smile:

Generally we try to direct "support requests" to our [forums](https://www.turnkeylinux.org/forum).

Although in this case, I'm not sure that's you'd get much useful help by posting there (I'm generally the one answering most of the posts over there too and I have no idea...). So whilst we do provide a preconfigured [Observium appliance](https://www.turnkeylinux.org/observium), we're certainly not the experts on Observium itself. You are probably best served by speaking directly with the [Observium community](https://docs.observium.org/community/) (either via their IRC or mailing list).

Before you reach out to them though, I encourage you to make sure that you are running the current Observium version (if you don't already have the latest version, perhaps updating may even be enough to resolve the issue?!). If you don't do that, I suspect that's possibly the first thing they'll tell you to do...

You can find the updating instructions in the [Observium docs](https://docs.observium.org/updating/) (FWIW the "Community Edition" instructions are right [near the bottom](https://docs.observium.org/updating/#community-edition).

I hope that points you in the right direction. I'll close this for now, but please do post back if you manage to resolve it, especially if there is something that we can do to improve our Observium, appliance OOTB. Good luck :smile:

**Closed by JedMeister** 2019-11-01 02:03 UTC
