### ISSUE TITLE
GameServer appliance

### ISSUE THREAD

**Issue by jesinmat** [turnkeylinux/tracker#1487] opened 2020-07-15 08:55 UTC
I'm working on an appliance for deploying game servers. It only contains a couple of scripts since it downloads newest game server files on boot (games update more frequently so they can't be part of the image). All scripts used (including game managing software) are open source, but games themselves are not - I hope this is not an issue. Game files are not contained in the TurnKey Appliance itself.

The appliance is available here: [TurnKey Gameserver](https://github.com/jesinmat/tkl-gameserver), it's based on Core 16.0.

It's almost finished, so I'd like to ask whether it's possible to get this appliance into turnkeylinux-apps once I polish it. I'll be happy to modify it according to your suggestions, should you have any.

**Comment by jesinmat** [comment] 2020-07-22 15:46
All work on the appliance is finished. If you have any suggestions for improving it, let me know. Otherwise, the appliance is ready to be merged into the repository.

**Comment by JedMeister** [comment] 2020-07-27 00:01
Hey @jesinmat - Apologies on my slow response, I've been a bit tied up...

Thanks for your submission. From a glance this looks cool! I don't think that it should be an issue that it leverages non-free (non-FLOSS) games, so longs as the contents are all free (as it sounds like they are).

I've had a super quick look over your code and it seems pretty solid. The only thing that jumped out at me was that it appears to only support interactive firstboot. I note that you mention non-interactive initialisation in your [readme]() but I couldn't see where/how it was actually being used (although perhaps I'm missing something?).

It's also worth noting, that a number of build types (the "headless" ones) that we support initially run the inithooks non-interactively (with random values); then re-run them interactively on first log in. It looks like that may not be supported with your set up - which we'd need to support.

There is also facility to [pre-seed the inithooks](https://github.com/turnkeylinux/inithooks#preseeding) which we'd want to support. And finally, the Hub only supports a basic set of pre-seeds. So there'd need to be a way of allowing it to complete initialization, even if a "proper" set of values weren't set on firstboot. 

Unfortunately, there isn't a specific/explicit way to know whether the inithooks are being run interactively or not. There are a couple of values which might help. There is `REDIRECT_OUTPUT` env var - which should generally only be set for headless builds. There is also the `RUN_FIRSTBOOT` env var which should only be set on firstboot. Both of these come from the [`/etc/default/inithooks`](https://github.com/turnkeylinux/inithooks/blob/master/default/inithooks). There is also `_TURNKEY_INIT` which should only be non-zero if the inithooks are being launched by `turnkey-init` (either the user has manually run that, or the headless build has triggered the interactive re-run). Unfortunately though there is one other scenario that we need to account for. When run from the TurnKey Hub, the "launch new server" form only supports the default inithooks values (e..g. `ROOT_PASS`, `APP_PASS`, etc...). One way to work around that would be to check for `APP_PASS` and if that's set but not `GAME` and `GAME_SERVER_NAME` then it's probably being launched from the Hub -. so the gameserver component would need to be skipped (or at least some of it) so as to ensure that the initialisation process doesn't "hang".

The only issue that leaves though is that then the initial config would not have been done for the gameserver component. So we'd need to ensure that that was documented. Ideally it'd be nice if we could make it really clear for users what was required. TBH, I'm not sure exactly the best way of doing that, but I'm sure it could be worked around. Perhaps a confconsole plugin?

Regardless of the above, in essence it looks great. As you'd likely be aware, we're currently still working on the v16.0 update of all appliances. I'd like to get the current apps updated before I look at adding new ones, but I'd certainly like to add this as a "v16.0" appliance.

Thanks again.

**Comment by jesinmat** [comment] 2020-07-27 15:32
Thank you for your reply. 

The game selection script can detect when it's running non-interactively without a game selected (headless without user data) and skips game selection.
The appliance supports pre-seeding, although it did only support full pre-seeding with all required parameters. I have now added support for partial pre-seeding (without the `GAME` variables, for example when running from TurnKey Hub).
No game server will be installed this way. User can now install the game server through a confconsole plugin in case no game server has been installed yet.

I have updated the README to reflect these changes.

**Comment by JedMeister** [comment] 2020-07-28 02:13
Great work. Thanks so much! This looks fantastic. :smile:

**Comment by JedMeister** [comment] 2020-07-28 02:57
Also, I meant to say that the logo you've created really stands out! It looks awesome! :smile:

**Comment by OnGle** [comment] 2020-11-09 12:24
Right I probably should get onto other stuff and I don't know whether or not we can squeeze this into this release but I'm gonna have a crack, we've got a bad habit of leaving stuff hanging, and this looks solid to me. I'm gonna have a bit more a look at the code here, and do a few tests. Fingers crossed we can get this one in!

Cheers for you hard work @jesinmat we massively appreciate it!

**Comment by OnGle** [comment] 2020-11-09 14:00
Alright unfortunately I'm unsure I'll be able to get this done tonight sorry mate. I've had a bit of a look and it looks pretty good. I do however have a few concerns which it might be good to have @JedMeister 's input on.

The first is that it clones your ``linux-gameservers`` repo on firstboot, this might cause some issues with bug reproducability, since we can't assume all turnkey users start off with the exact same environment it might be best to provide this functionality via a confconsole plugin or the like and perform the initial clone in the ``conf.d/main`` script, just not performing init until firstboot.

The second concern is that it performs an ``apt update`` and ``apt upgrade`` on first boot (in your ``linux-gameservers`` project), ultimately this *might* be required, especially in the case for example minecraft where it'll need to install java but the apt cache has been cleared as part of our build, but it'd be nice if we could avoid it if at all possible for the same reason as the previous point in addition to the fact that it just speeds up first boot.

I'll first wait for @JedMeister 's input, and we'll move on from there. In any case I'm confident we can sort this out quickly :+1:

**Comment by OnGle** [comment] 2020-11-10 10:34
Alright, I've made those tweaks, repo is here https://github.com/OnGle/tkl-gameserver/tree/tweaks I'll ping JedMeister and fingers crossed we can get this in this release!

**Comment by jesinmat** [comment] 2020-11-11 09:23
Thanks for the update! I hope everything's alright now, but I'll be happy to make additional changes if necessary.

**Comment by jesinmat** [comment] 2020-11-11 11:49
Correct me if I'm wrong @OnGle , but it seems like your changes removed the possibility of cloning a custom branch from linux-gameservers repo or specifying a new repo (this was possible by providing GAME_REPO_URL and GAME_REPO_BRANCH userdata variables).
While this makes no difference now, I implemented it in case there's an "experimental" game server not merged into master yet or in case a user forks the gameservers repo to add another game server and wants to run it in the appliance first to verify it.

**Comment by OnGle** [comment] 2020-11-13 02:41
No dramas mate! (And sorry for the slow reply, I'm really bad at checking my github notifications)

You are indeed correct and raise a good point, the reasoning behind me removing the install ``clone_or_update_gameservers`` function was because after initial install and moving to a manual update, it appeared not to update automatically anyway (because of this check https://github.com/jesinmat/tkl-gameserver/blob/master/overlay/usr/local/bin/gameserver-init#L17 ) so I just dismissed it when moving to the ``conf.d/main``. But I completely glossed over the fact it allowed the user to use the preseeds to use a different branch or fork. So my proposed solution is to:

1. provide an extra interactive inithook for people wishing to specify a separate url/branch but prefill with your url & master, only performing any changes if the user specifies different values.
2. provide an additional confconsole entry for changing these values at a later date.

Things are so close now I might make these changes and just adjust if you have any further concerns :)

**Comment by OnGle** [comment] 2020-11-18 03:56
I'm going to close this, if you've got any further feedback, issues or improvements to add @jesinmat please add an issue to https://github.com/turnkeylinux/tracker/issues or provide a PR to https://github.com/turnkeylinux-apps/tkl-gameserver :+1:

**Closed by OnGle** 2020-11-18 03:56 UTC
Labels: new-appliance
