### ISSUE TITLE
Cant view youtube files in Wordpress

### ISSUE THREAD

**Issue by ejgutierrez74** [turnkeylinux/tracker#1416] opened 2020-02-15 11:28 UTC
I have a  plain new installation of TurmkeyWordpress.
Im a teacher on a post obligatory institute and we are facing two problems:

1 - Students cant add you tube videos in their pages, it doesnt work.... The only way was adding the code ( in the video on youtube -> right click .> copy insert code) ... And then in wordpress Add new block -> custom html -> paste the code.. So this way works...

2 - Another group are facing that video appears as not avalaible, but if you go to youtube the video works fine and its avalaiible....For example: https://www.youtube.com/watch?v=mtym36PG6R8 if you add this video it seems ok in your page, but when you play it it says video unavalaible...

Any ideas about this errors ?

Thanks

**Comment by JedMeister** [comment] 2020-02-16 22:34
FWIW this is our "issue tracker" for bug reports and feature requests.

TBH, this doesn't seem like a bug in TurnKey, so I would consider this a support request. Normally support requests are best posted on our [forums](https://www.turnkeylinux.org/forum/). So I'm going to close this (if it turns out that there is a bug, we can always reopen it).

Anyway, seeing as we're here, I'll respond....

1. This sounds like expected behaviour to me. TurnKey is a vanilla WordPress install with no additional custom config (or any 3rd party plugins). I'm pretty sure the functionality you are seeking will require some specific config at least (perhaps even a plugin). If you are sure that it should "just work" in a vanilla WordPress, please share some resources and I'm happy to look into it further.

2. That sounds more like some sort of networking issue. Where are you running the WordPress server?

**Closed by JedMeister** 2020-02-16 22:34 UTC
