### ISSUE TITLE
OTRS appliance breaks after trying to log in as admin.

### ISSUE THREAD

**Issue by qq7** [turnkeylinux/tracker#1238] opened 2018-11-01 21:02 UTC
After trying to log in into admin dashboard, a server stops responding and I'm unable to ssh into it. `ssh_exchange_identification: read: Connection reset by peer`

**Comment by OnGle** [comment] 2018-11-08 02:28
Was unable to reproduce on LXC builds locally, issue probably relating to buildtype or hub.

**Comment by qq7** [comment] 2018-11-14 22:12
Just tried to do the same thing in VirtualBox, and it's definitely there. Can you actually log in? For me it doesn't go any further than pressing log in button.

**Comment by JedMeister** [comment] 2018-11-14 23:08
I've reproduced from the Hub. Thanks for confirming that it also affects VM build too.

FWIW, my initial testing (and @OnGle's too I suspect) I used the LXC container, which for some reason appears to not be affected?!.

From my brief bit of diagnosis (on Hub servers - I initially reproduced on a t2.micro, but also tested t2.small just in case it was pure lack of RAM) it appears that there is a memory leak somewhere in the code (perhaps caused by our custom config?). That causes the OTRS process to chew up all the RAM and causes the server to become unresponsive. It appears that eventually, the offending process crashes (or perhaps the kernel OOM killer kills it?) and the server becomes responsive again (although Apache doesn't appear to fully recover).

If you have time @qq7 could you please try installing the otrs Debian packages on LAMP and see if you can recreate it with the Debian default config? That will assist us to understand whether it's something we're doing wrong, or whether it's actually a fault with the Debian packages. FWIW I did check the Debian tracker and couldn't find any other similar bugs reported.

**Comment by JedMeister** [comment] 2018-11-14 23:21
Hey @qq7 

Actually, I just had a quick look and it seems that there is an update to the OTRS Debian package. The [Debian package page](https://packages.debian.org/stretch/otrs2) notes the latest version as `5.0.16-1+deb9u6` but our appliance has `otrs2 5.0.16-1+deb9u5` installed (see the [v15.0 OTRS manifest](https://releases.turnkeylinux.org/turnkey-otrs/15.0-stretch-amd64/turnkey-otrs-15.0-stretch-amd64.manifest)).

So perhaps if you could just try updating to that new package (on our existing OTRS appliance) and see if that fixes the error? As it's not a security update, it won't be auto installed.

Also, I notice that Debian has an OTRS metapackage, simply called [`otrs`](https://packages.debian.org/stretch/otrs). It won't really make much difference, but perhaps we should actually be installing that instead (it depends on the `otrs2` package which actually contains otrs)? Probably not a significant issue for now though...

**Comment by qq7** [comment] 2018-11-17 12:10
Just tried rebuilding `otrs` and the app seems to work pretty normally! Not sure if this is normal behavior, but there's a warning which says that OTRS Daemon is not running, so I needed to run /usr/share/orts/bin/Cron.sh as otrs user for it to disappear

**Comment by JedMeister** [comment] 2018-11-18 04:21
Hmm ok. So it sounds like ti may have been a bug in the OTRS package (see my notes above about the updated Debian package). Thanks for testing and confirming that seems to work. We should rebuild as v15.1. 

Also, re the daemon not running, I', not sure why that is. Perhaps we need to do something so that runs by default at boot?

**Comment by JedMeister** [comment] 2018-12-03 02:07
This no longer appears to be an issue. Closing...

**Closed by JedMeister** 2018-12-03 02:07 UTC
Labels: ami (build type), bug, confirmed, iso (build type), otrs, ova (build type), vmdk (build type)
