### ISSUE TITLE
(Jessie RC1 Lapp)  Reached Target Shutdown not Rebooting

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#368] opened 2015-05-19 10:41 UTC
First Boot from ISO.  Install proceeds well.  Grub Installed etc.

However, when "do you want to reboot" the machine hangs with 
"Reached Target Shutdown".

Hard Reset does bring it around but this should proceed as it has in the past.

This is on LAPP from TKLDEV Jessie RC1 14

**Comment by JedMeister** [comment] 2015-05-19 11:47
Did you forget that you have already reported this (#345) ! :smile: And I closed that because it was a duplicate of #339! :smile: :laughing: 

It's all good; thanks for reporting anyway! BTW it's actually not hanging. It's just not powering off and rebooting. Essentially it has halted (i.e. it has shutdown but not powered off). I guess ofr all intents and purposes though that is hanging I guess...

**Closed by JedMeister** 2015-05-19 11:47 UTC

**Comment by l-arnold** [comment] 2015-05-19 12:11
I think I searched for "reached target shutdown" and "open"..  

You are correct about the hades like place, not so bad and not quite good.  Not seeing harm.  Just expecting a reboot is all.
