### ISSUE TITLE
Etherpad on Proxmox - 502 error and NPM process not running

### ISSUE THREAD

**Issue by efaden** [turnkeylinux/tracker#891] opened 2017-07-23 17:44 UTC
With a fresh install I'm getting a 502 error and the NPM process doesn't seem to be running.  Thoughts?

**Comment by JedMeister** [comment] 2017-07-23 21:24
Hi @efaden - can you please clarify which particular appliance and which version.

**Comment by efaden** [comment] 2017-07-24 01:11
The one downloaded through proxmox.  The filename is debian-8-turnkey-etherpad_14.1-1_amd64.tar.gz ... I did a fresh install and followed the GUI.  After that nothing is running on port 8000... so I get a 502.

**Comment by JedMeister** [comment] 2017-07-24 04:10
Thanks for the extra info.

Unfortunately, that's a known issue. The problem is that we used pm2 to manage node services in v14.1 and unfortunately it appears that pm2 is a bit buggy. For the upcoming v14.2 release we've gone back to using the init system. Hopefully the new appliance should be available within the next week or 2.

In the meantime, you have a couple of options. Probably the easiest one is to disable pm2, download the sysvinit script and enable it.

Assuming you are already logged into you appliance as root:
````
service pm2 stop
update-rc.d pm2 disable
SCRIPT=/etc/init.d/etherpad
DL=https://raw.githubusercontent.com/turnkeylinux-apps/etherpad/master/overlay${SCRIPT}
wget -O $SCRIPT $DL
chmod +x $SCRIPT
update-rc.d etherpad defaults
````

And then reboot and hopefully you should be all good. 

Please note, I have tested this script on the new (yet to be released) build and it works great, but I wrote the above off the top of my head so hopefully I haven't made any mistakes. Let me know how you go and if you have any errors, please post them and I'll see what I can do for you.

**Comment by JedMeister** [comment] 2017-07-24 04:13
Also WRT to `npm` you should be able to run that via the commandline. Although IIRC it's actually installed for the `node` user account, so you made need to run it as the node user. E.g. something like this:
````
su - node npm ...
````

**Comment by efaden** [comment] 2017-07-24 23:09
Thanks!  Any idea when you'll be putting up the new release?  I'm just going to use the script for now.  Thanks!

**Comment by JedMeister** [comment] 2017-07-25 01:07
No problem.

The ISO is currently sitting in an AWS bucket ready to be published. At this point we plan to publish what is ready on Wed. So if all goes according to plan we'll build the optimized/alternate builds (inc the Proxmox container) Thur and publish Friday or Monday next week. So it should be available from the mirror (and therefore via Proxmox download) mid next week... :crossed_fingers:

**Comment by JedMeister** [comment] 2017-08-02 10:33
The new appliance should be available now and this issue should be fixed. So I'm going to close this for now. Please feel free to reopen if it's still an issue.

**Closed by JedMeister** 2017-08-02 10:33 UTC
Labels: bug, etherpad, workaround
