### ISSUE TITLE
Web2Py Upgrade Fails

### ISSUE THREAD

**Issue by seefor** [turnkeylinux/tracker#323] opened 2015-03-31 23:39 UTC
Trying to upgrade to 2.10.1 from 2.7

Keep getting Tracker issue and can't click the link to get more information
Thanks,
Sif

**Comment by JedMeister** [comment] 2015-04-01 12:18
So are you trying to update Web2Py on a running appliance or in the build code (and build a new ISO with 2.7 already included)?

If in the build code then if you can give me a little more info I'll try to help as much as I can.

If on the other hand you are working on an installed and running server then I suspect that upstream might actually be more help than me... 

I know that's not a great answer but we're a small team and running way behind on updating the appliances. We need to focus our time on that as much as possible so we can get the new Jessie based appliances (with updated apps) out ASAP.

**Comment by seefor** [comment] 2015-04-01 13:28
Dude not a problem at all @JedMeister 
I'm doing this in the build version you have on the site which is currently running "2.7.4-stable+timestamp.2013.10.14.15.16.29" version 2.10.1 came out yesterday and I wanted to upgrade it.

As an FYI I was looking at how to build my own TurnKey Linux so I can do it from scratch as well and learn the secret sauce as well :)
I did find the TKLDev going to read up on that in the coming weeks.

Any help you can give me with the "upgrade" in the UI of Web2Py would be great.
Thanks in advance
Sif

**Comment by JedMeister** [comment] 2015-04-01 23:00
Ok awesome. Well first thing I suggest is get your head around TKLDev (there's a page [here](http://www.turnkeylinux.org/docs/tkldev) in our docs that has lots of links to different info).

Once you have an understanding of what is going on; then I suggest that you have a good look at the [Maintaining an appliance](https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/development/maintenance.rst) doc page.

With regard to Web2Py specifically; You can see the build code [here](https://github.com/turnkeylinux-apps/web2py/). However as Web2Py is a framework; the Web2Py appliance is consider a 'base' appliance (i.e. other appliances may be built on top of it) so you will actually find some of it's build code in '[common](https://github.com/turnkeylinux/common)' (e.g. [web2py conf script](https://github.com/turnkeylinux/common/blob/master/conf/web2py)). This means that you will probably (almost certainly) need to tweak both the Web2Py repo and Common.

If you can get it all working then that will be super-duper awesome and please issue a pull request(s)! :smile:

**Comment by JedMeister** [comment] 2015-05-15 09:31
Hopefully this won't be an issue when building with a Jessie base...

**Comment by JedMeister** [comment] 2015-06-12 02:28
@seefor Sorry this issue hasn't been updated sooner... As of a few weeks ago the v14.0 [Web2Py appliance](https://github.com/turnkeylinux-apps/web2py) builds fine. I haven't double  checked it for regressions since then but i would anticipate any issues. Please feel free to let me know if there are.

Also if you want pointers on building your own updated ISO then have a look at [this blog post](https://www.turnkeylinux.org/blog/howto-build-isos-with-tkldev).

I'm going to close this issue for now, but if you have further issues please feel free to reopen.

**Closed by JedMeister** 2015-06-12 02:28 UTC
Labels: bug, build, web2py
