### ISSUE TITLE
Rails apps MariaDB Specified key was too long

### ISSUE THREAD

**Issue by qq7** [turnkeylinux/tracker#985] opened 2017-12-08 10:36 UTC
This error occurs on running migrations in Rails MariaDB appliances: Redmine, tracks
Upgrading MariaDB to 10.2 is the best possible resolution for this so far

Occurs in redmine on
`+ bundle exec rake db:migrate RAILS_ENV="production"`

Body:
```
-- add_index(:wiki_pages, [:wiki_id, :title], {:name=>:wiki_pages_wiki_id_title})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE  INDEX `wiki_pages_wiki_id_title`  ON `wiki_pages` (`wiki_id`, `title`) 
/opt/redmine/db/migrate/028_create_wiki_pages.rb:8:in `up'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE  INDEX `wiki_pages_wiki_id_title`  ON `wiki_pages` (`wiki_id`, `title`) 
/opt/redmine/db/migrate/028_create_wiki_pages.rb:8:in `up'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Mysql2::Error: Specified key was too long; max key length is 767 bytes
/opt/redmine/db/migrate/028_create_wiki_pages.rb:8:in `up'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by JedMeister** [comment] 2017-12-12 07:32
@qq7 - Please excuse me if I'm repeating stuff you already know. I just want to be really clear and explicit and make sure that you understand what is going on. If you don't understand anything, or think I'm wrong on any points, please do not hesitate to question! FYI I'm using "MySQL" and "MariaDB" interchangeably here. This has all been tested, starting from your [Redmine v15.0 branch](https://github.com/qq7/redmine/tree/v15.0).

## Background

From the research I've done, it's pretty clear that essentially this issue is caused by the move to `utf8mb` text encoding. Until fairly recently, `utf8` has been the standard, but due to the use of emojis, `utf8mb` encoding is required to display all the characters properly. FWIW I've also heard `utf8mb` called "utf8 extended", but we'll stick with the name that MySQL uses!

Up to and including MySQLv5.6/MariaDBv10.1; 767 bytes was the general limitation for InnoDB table keys. In MySQLv5.7/MariaDBv10.2 that has been bumped to 3072 bytes - hence why it works ok there. So you rightly suggest that using MariaDB >= v10.2 would be a solution. However, using the packages provided by Debian Stable is (almost) always our preferred option. So let's leave that option off the table unless we run out of other options. I'm happy to provide more detail on that rationale if you want, but another place and time...

## Implications

I'm not 100% sure, but I assume that in Redmine's data, the MySQL DB rows are allowed to be up to to 255 characters. That is fine with `utf8` as each character is 3 bytes; 3 x 255 =  765. So there are still a couple of bytes to spare, which incidentally is important as MySQL needs up to a couple of bytes for storing the row length.

However, with `utf8mb` text encoding, each character is 4 bytes; 4 x 255 = 1020 (hence why it complains that it's over the 767 bytes limit). MariaDBv10.1 does actually support the larger 3072 byte prefix limit on tables that use `DYNAMIC` or `COMPRESSED` row format. Unfortunately though, it's not possible to set the DB to use that by default on all tables (that global setting wasn't introduced until v10.2). So it needs to be done on a table by table basis. It can be done initially when the table has been created, or existing tables can be modified.

## Potential Workarounds and Solutions

As noted above, we've already discarded the workaround of upgrading the MariaDB version (unless there are no other good ones, but I reckon there are!).

One option may be to change the default encoding back to `utf8`. That would work, but would also likely have unintended consequences. Mostly they would only be aesthetic, such as characters not displaying properly, but it's still not ideal.

Another option is to manually reduce the max key size to 191 (4 x 191 = 764). But again, that may have some unintended consequences. Without knowing more about Redmine, that may be relatively minor. Or it could cause big dramas at some point down the road. I'm not really sure, but unless someone from Redmine explicitly said it was ok, I'm not really keen to find out! (I also do support...! :smile: ).

So my preferred option is to adjust each row to be `DYNAMIC`. As I noted above, that's not possible globally in v10.1, but it works fine on a table by table basis.

## Implementation

With that in mind, I have tested updating the config to support the larger key size. I also modified the relevant Ruby DB initialisation files so that they explicitly add the `ROW_FORMAT=DYNAMIC` option to each row when it's created. All in all, it works a treat!

FWIW, I've pushed the tested code back to GH so you can have a look. The initial DB config changes are done [here](https://github.com/JedMeister/redmine/blob/zhenya-v15.0/conf.d/main#L12-L20). If we hit this issue in multiple Rails based apps, then we should probably push those specific changes to common.

I then used find and sed ([here](https://github.com/JedMeister/redmine/blob/zhenya-v15.0/conf.d/main#L37-L39)) to adjust all the times the `create_table` function is called, and add `, options: 'ROW_FORMAT=DYNAMIC'`.

Like I say, that works fine. But I have concerns about the future. E.g. if someone tries to update the version of Redmine, it will fail (with the same issue we're encountering here). So what I thought may be a better solution is to monkey patch the Rails `create_table` function so that it always sets the tables as dynamic. What do you think?

**Comment by JedMeister** [comment] 2017-12-12 07:54
Hey, it looks like [this](https://github.com/rails/rails/issues/9855#issuecomment-57665404) might be exactly what we're after?!

**Comment by JedMeister** [comment] 2017-12-18 07:31
Seeing as we appear to have found a workaround for Rails based apps, I'll add the workaround tag. Once we've got all the appliances building successfully, then I'll close it altogether, but until we know for sure that it doesn't affect others, we should keep it open IMO.

FWIW @OnGle has now hit this exact issue in one of the apps he's been working on. Roundup I think!? I'll add it here now anyway. 

@OnGle - if I got that wrong, please adjust as necessary. Cheers.

**Comment by picasso250** [comment] 2018-03-08 04:56
If you use mysql, what you only need to do is 
`$find ./ -type f -exec sed -i "/create_table / s| do |, options: 'ROW_FORMAT=DYNAMIC' do |" {} \;`

**Comment by JedMeister** [comment] 2018-05-10 06:49
Hey @picasso250 - I just noticed your comment, sorry I missed it previously. 

That's a pretty good suggestion if you have SQL dumps that you wish to update! Although as `./` will always be your current directory, it could potentially have unintended consequence couldn't it?!

**Comment by JedMeister** [comment] 2018-05-30 08:00
Seeing as we're addressing (or have already addressed) this in specific appliances, I'm going to close this specific issue for now.

**Closed by JedMeister** 2018-05-30 08:00 UTC
Labels: mysql, rails, redmine, roundup, tracks, workaround
