### ISSUE TITLE
Configuration Console display messed up on boot

### ISSUE THREAD

**Issue by sackwort** [turnkeylinux/tracker#520] opened 2015-12-13 15:16 UTC
Turnkey Lamp Stack (turnkey-lamp-14.0-jessie-amd64.ova) imported into Virtualbox 5.0.2, on Linux Mint 17.3 64-bit.

After booting, the Configuration Console displays all right for a few seconds, and then some more processes happen and the display becomes "messed-up". Pressing the Return key makes the Config Console reappear properly. Please see attached screenshot.

![configconsole](https://cloud.githubusercontent.com/assets/6024422/11767682/7055f186-a1ac-11e5-9a8c-ef5e97f5e0b6.png)

**Comment by JedMeister** [comment] 2015-12-13 22:23
Hi @sackwort, Thanks for reporting. 

Actually this is a known issue (duplicate of #338). As noted there it is caused by the fact that SystemD is a synchronous initialisation system. So any "fix" would only be a workaround (that would slow the boot process down). Although it's not very pretty it is only cosmetic so we are not planning on doing anything about it. 

If you (or someone else) wants to take it on and see if you can work out a fix I'm open to reopening this but I'm going to close it for now.

**Closed by JedMeister** 2015-12-13 22:23 UTC
Labels: bug, confconsole, confirmed, won't fix
