### ISSUE TITLE
Cycling "Your Connection is not Private" warnings

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#457] opened 2015-09-09 15:14 UTC
Normally when a "default" TKL Cert is accepted the "acceptance has some legs" and one can do their work after "accepting and proceeding".

Just did a TKLBAM Restore and the cycle in Chrome is incesessant.

Normally I put a full cert on my main Work Focus (the App) but not Webmin/Webshell/Adminer etc.

Would be worth testin this situation on some other aps and doing some TKLBAM restores to see if that is he root of the problem.

**Comment by JedMeister** [comment] 2015-09-09 21:16
Can you please describe what is actually happening? Do you mean that you constantly have to accept the "self signed" browser warning everytime you do something in an https session?

If you are talking about having to accept the warning for every session then AFAIK that is changed browser behaviour and doesn't have anything to do with TurnKey...

**Comment by l-arnold** [comment] 2015-09-09 21:32
Ran a TKLBAM restore to new build
Moved My IP on the new build to match the old.

My Cert (on Odoo ports 443/80) worked fine.
All my other ports using Default TKL Seeds basically went bonkers.  Could get a page or two before I would get the "uncertified" cycle  (accept/reject etc).  

Tried closing tabs opening new ones.  Closing Browsers opening new ones etc.

Something to do w/ Site/Page identity.  Might be changing.  Things in the browser.  Things on the site.  Very trying though on the user end when trying to test other things.  Expectation is that others may have similar experience.

Had I not changed the IP it probably would have been OK.  Needed to change the IP to test the Main Cert and its movement through TKLBAM.

**Comment by JedMeister** [comment] 2015-09-09 21:50
TBH I am not 100% sure but my guess is that the self-signed auto generated certs are not backed up.

That would make sense as to your browser the IP has stayed the same but the cert has changed. There is not a legitimate reason for that to happen that I can think of; same scert from a different IP would be ok, but different cert for different IP - especially during a current session would bea bad thing... IMO If that happened in the real world (an https website with a self signed cert suddenly changed it's cert) you would want it to be a problem as it would quite possibly be caused by a man-in-the-middle attack; i.e. someone between you and the website pretending to be the website...

**Comment by l-arnold** [comment] 2015-09-10 01:25
I understand for sure - I just wanted a work around for my own situation..  That said...  it is important also to keep your users happy also and not scare  them when the do use TKLBAM.  Not sure the solution.

**Comment by JedMeister** [comment] 2015-09-10 21:36
TBH I don't think that there is an immediate solution beyond using a proper CA issued cert...

**Comment by JedMeister** [comment] 2015-10-20 23:43
Closing

**Closed by JedMeister** 2015-10-20 23:43 UTC
