### ISSUE TITLE
Web2PY deployment issues

### ISSUE THREAD

**Issue by seefor** [turnkeylinux/tracker#311] opened 2015-03-20 19:22 UTC
The Admin interface does not looks correct, it looks like it's missing a lot of data.

**Comment by JedMeister** [comment] 2015-03-23 11:18
Hmm someone else has reported a similar sounding issue: #314

**Comment by seefor** [comment] 2015-03-24 21:29
You can access it via HTTPS but it looks like the following:
[Imgur](http://i.imgur.com/FDEFZ9U.png?1)

**Comment by JedMeister** [comment] 2015-03-25 00:00
Yep same as the other one...

Looks like the CSS is getting lost somewhere...

**Comment by JedMeister** [comment] 2015-03-25 00:31
There is a fix. See https://github.com/turnkeylinux/tracker/issues/314#issuecomment-85757430

**Comment by JedMeister** [comment] 2015-03-25 02:10
I hope you don't mind I just changed the title. 

Also I am going to close this as it is a duplicate of #159 & #314. I will leave the most recent one (#314) open for now until all you guys confirm that the fix works and that you are up and running...

**Closed by JedMeister** 2015-03-25 02:10 UTC
Labels: bug, web2py
