### ISSUE TITLE
secalerts inithook threw an error during turnkey-init

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#532] opened 2015-12-23 13:08 UTC
I just reran the inithooks on an appliance I was testing and added an email for secalerts. It failed:
````
info [secalerts.sh]: configure_alias root tester@testing.com
info [secalerts.sh]: configure_cronapt MAILON output
info [secalerts.sh]: configure_cronapt MAILTO root
info [secalerts.sh]: send_enabled_notification root
info [secalerts.sh]: enable_security_alerts tester@testing.com
Traceback (most recent call last):
  File "/usr/lib/inithooks/bin/secalerts.py", line 92, in <module>
    main()
  File "/usr/lib/inithooks/bin/secalerts.py", line 88, in main
    system(cmd, email)
  File "/usr/lib/python2.7/dist-packages/executil.py", line 56, in system
    raise ExecError(command, exitcode)
executil.ExecError: non-zero exitcode (6) for command: /usr/lib/inithooks/bin/secalerts.sh 'tester@testing.com'
````

I then reran it manually (using the same bogus email address) and it appeared to complete fine!?
````
root@suitecrm ~# /usr/lib/inithooks/bin/secalerts.sh 'tester@testing.com'
info [secalerts.sh]: configure_alias root tester@testing.com
info [secalerts.sh]: configure_cronapt MAILON output
info [secalerts.sh]: configure_cronapt MAILTO root
info [secalerts.sh]: send_enabled_notification root
info [secalerts.sh]: enable_security_alerts tester@testing.com
root@suitecrm ~# echo $?
0
````

**Comment by qrntz** [comment] 2016-03-13 18:05
Hub returns

    HubServer.SecAlertsError:Failure enabling security alerts: 255

when [connecting via HTTPS](https://github.com/qrntz/inithooks/commit/79403fd9f053c25894cb1f03aadebe370ccb812a#diff-dbc080bf209bcba7ff062b7c51bf5f37L61), which causes curl to return error 22, which allows me to reproduce the issue. The exit code is zero when using HTTP and no error is displayed.

OTOH, your case has curl fail because of a DNS resolution issue (exit code 6) which was evidently temporary, causing the same curl invocation to return zero just a moment later when DNS was working fine.

The general case should be fixed by the PR, however it seems some Hubside attention is warranted.

**Closed** 2016-09-12 00:44 UTC
Labels: bug, inithooks
