### ISSUE TITLE
Confconsole letsencrypt invalid field verification

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#767] opened 2017-02-01 02:58 UTC
````
root@lamp ~# apt-cache policy confconsole
confconsole:
  Installed: 0.9.4+94+gc2196a0
  Candidate: 0.9.4+94+gc2196a0
  Version table:
 *** 0.9.4+94+gc2196a0 0
        900 http://tkl-dev-test.s3-website-us-east-1.amazonaws.com/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     0.9.4+54+g99603c7 0
        850 http://archive.turnkeylinux.org/debian/ jessie/main amd64 Packages
````

Confconsole letsencrypt will error when the `Common Name` field is not specified with the following message:

```
end of string while processing type of subject name element #5
problems making Certificate
```

**Comment by JedMeister** [comment] 2017-02-01 03:09
related to #546 & #369

**Comment by JedMeister** [comment] 2017-02-01 23:20
Should be fixed in the latest dev-test package. More details here:
https://github.com/turnkeylinux/confconsole/pull/8#issuecomment-276803287

**Comment by JedMeister** [comment] 2017-02-08 06:11
I'm closing this now as I can't reproduce it anymore so I assume it's been fixed.

**Closed by JedMeister** 2017-02-08 06:11 UTC
Labels: bug, confconsole, inprogress
