### ISSUE TITLE
On First Login Names And Paswords aren't set Redis

### ISSUE THREAD

**Issue by timcoolmode** [turnkeylinux/tracker#1392] opened 2019-12-28 02:34 UTC
Typically on a first login the system asks for user names and/or passwords for setting up systems. On the redis system that doesn't happen.

**Comment by JedMeister** [comment] 2020-01-01 22:49
Hi @timcoolmode - It certainly should be asking for both the root password and the redis admin user password (for use with Redis Commander).

If that's not the case for you, could you please confirm which build you are using and where it's running (e.g. OVA build on local VirtualBox, [Hub server](https://hub.turnkeylinux.org/), etc). FWIW, I'd normally also ask that you confirm which particular release you are running, but seeing as there is only one for Redis, then I know it's v15.0! :smile:

**Comment by timcoolmode** [comment] 2020-01-02 02:12
I'm doing it on proxmox not sure what other questions you are looking for me to answer. 

Willing to help. 
Tim

**Comment by JedMeister** [comment] 2020-01-02 03:40
Ah ok, so is it a container (e.g. template downloaded via the PVE UI)? Or a VM (e.g. installed from ISO)? As soon as I know, I can try to recreate your issue.

Also out of interest, which version of PVE are you running? FWIW, I'm still running v5.4 and the v15.0 TurnKey Redis container appears to work fine for me.

As you seem to be expecting, on first boot, it should ask you for passwords etc. If it's a container though, it won't ask for a root password (as that is set on the host at launch time). As you possibly already know, to access the first boot scripts, you can do that via the PVE web console (e.g. NoVNC window) or by logging in via SSH (my personal preference).

If it's a VM, then you should be asked for a root password on firstboot too (as the first question IIRC). For VMs, generally it's easier to run through the firstboot questions within the PVE web console (e.g. NoVNC window) as no root password is set and the IP address is initially set dynamically.

**Comment by timcoolmode** [comment] 2020-01-02 11:48
Yes it's a container. I'm using PVE 6.0-4

**Comment by JedMeister** [comment] 2020-01-03 00:49
Hmmm, there seem to have been a few issues reported recently regarding containers running on Proxmox v6.x, which I can't recreate (on Proxmox v5.x). I wonder if this is another errant issue somehow related to the interaction between TurnKey v15.x and PVE v6.x?

Without further investigation and testing, I can't at all be sure what the actual cause is. Regardless, I wouldn't have expected changes in Proxmox to be the cause of this particular issue (although who knows... perhaps?).

FWIW, you should be able to interactively rerun all of the firstboot inithooks by running `turnkey-init`, or just the redis specific ones, via `/usr/lib/inithooks/bin/redis.py`. Alternatively, you could retry running the redis inithooks non-interactively by passing all the answers via switches. See `/usr/lib/inithooks/bin/redis.py --help` for info on that.

Could you perhaps try running the Redis specific inithook (i.e. `/usr/lib/inithooks/bin/redis.py`) and share any output you get with me? E.g. let me know if it works as it should, or whether it throws an error. If it throws an error, could you please paste the full output here.

**Comment by JedMeister** [comment] 2020-09-08 00:10
I was not able to reproduce this issue in our latest v16.1 appliance release, however I did discover another issue (in v16.0 - #1503 - patched in v16.1) which may have been related.

So hopefully this should be resolved as of our Redis v16.0/v16.1 release. So I'm closing this for now. If you or anyone experiences this (on v16.1+), please feel free to provide further info and we can reopen this issue.

**Comment by SupaYoshi** [comment] 2020-11-08 15:09
Hi I am being faced with this issue, running the latest proxmox release and turnkey-redis_16.1-1 on proxmox pve-manager/6.2-14/2001b502 (running kernel: 5.4.65-1-pve)

**Comment by JedMeister** [comment] 2020-11-08 23:35
@SupaYoshi - hmm, thanks for posting, plus the screenshot of the Confconsole stack trace. That's clearly an issue and I've opened a new issue and posted a workaround for now.

I've just had a closer look at the password setting code and I can see an (the?) issue already. TBH I'm not sure how I managed to miss this before?! It's weird... Anyway, the [workaround noted above](https://github.com/turnkeylinux/tracker/issues/1392#issuecomment-570419585) should still apply.

**Comment by JedMeister** [comment] 2020-11-09 04:58
As per my previous comment, I've reproduced this issue and can confirm. TBH, I'm not really sure how I wasn't able to previously...

**Comment by JedMeister** [comment] 2020-11-09 06:24
Please note that I have now refactored the inithook quite significantly and it will be included in the next release.

**Closed** 2020-11-18 22:59 UTC
Labels: bug, redis

**Comment by masoudei** [comment] 2020-12-26 21:36
yes still not working password for Redis-commander in web interface not questioned during init hook.. and still can't access to the Redis-commander web UI

**Comment by tales-desde-mileto** [comment] 2020-12-30 12:12
Same error. I am working with proxmox 6.3-3, lxc, turnkey-redis-16.1-buster-amd64

You can find the auth-key by searching for it in the process. Like this:

`redis    15190  0.0 10.5 603840 55236 ?        Sl   12:01   0:01 node /usr/local/bin/redis-commander --redis-host=127.0.0.1 --redis-password='xxx' --port=8082 --http-auth-username=admin --http-auth-password=turnkey2 --address=127.0.0.1`

Then I can access with this:
User: admin
Password: turnkey2

If the problem is redis password, is in --redis-password in same process line
Or check the init file:
/etc/init.d/redis-commander

Or try: 
turnkey-redis-pw get
turnkey-redis-pw set XXXXXXX

I hope you find it useful.
