### ISSUE TITLE
Jessie - Postgresql TKLDEV

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#377] opened 2015-05-25 22:38 UTC
Postgresql Does not run in TKLDEV.  Failed Twice same place: Looks like This tripped it up:
E: Unable to locate package postgresql-9-1-postgis
E: Couldn't find any package by regex 'postgresql-9.1-postgis'

- Bitvise xterm - 192.168.1.123:22
Setting up linux-base <3.5> ...
Setting up linux-image-3.16.0~4~amd64 <3.16.7-ckt9-3~deb8ul> ...
/etc/kerne 1/postinst.d/initramfs-tools:
yarning: Deferring update-initramfs -c -t -k 3.16.0~4~amd64 -b /boot
Setting up linux-image~amd64 <3.16+63) ...
Beading package lists... Done
Building dependency tree
Beading state information... Done
E: Unable to locate package postgresql-9-1-postgis
E: Couldn't find any package by regex 'postgresql-9.1-postgis'
Traceback <most recent call last>:
File ,p/usr/lib/fab/wrapper.py", line 34, in <module>
C1iUrapper.nain < >
File ,p/usr/lib/pytbon2.7/dist-packages/pyproject.py°, line 388, in main
commands.run<name, args>
File ,p/usr/lib/pytbon2.7/dist-packages/pyproject.py°, line 261, in run
command-module .mainO
File ,p/usr/lib/fab/pylib/cmd_install.py'p, line 129, in main
installer. instalKpackages, ignore .errors)
File ,p/usr/lib/fab/pylib/installer-py°, line 267, in install
self._install<packages, ignore.errors)
File ,p/usr/lib/fab/pylib/installer.py°, line 137, in _install
self .cbroot-system<”apt-get,p, *<args + packages>>
File ,p/usr/lib/python2.7/dist-packages/cbroot -py”, line 80, in system
executil.system<*self-_prepare_command<*command>>
File ,p/usr/lib/python2.7/dist-packages/executil.py”, line 56, in system
raise ExecError<command, exitcode>
executil.ExecError: non-zero exitcode <100) for command: cbroot '/turnkey/fab/pr
n x

**Comment by l-arnold** [comment] 2015-05-25 22:55
Appears to be the GIS addon for Postgres.  Just removed it locally from /plan/main and am trying a build right now.  Seems to be moving along.

**Comment by l-arnold** [comment] 2015-05-25 22:59
Appears that present build is only for Wheezy:
http://trac.osgeo.org/postgis/wiki/UsersWikiInstall

**Comment by JedMeister** [comment] 2015-05-26 04:02
Currently building with Wheezy is tricky. Next time we do this we will do it better and not commit straight to the 'master' branch; we'll have a 'stretch' or 'dev' branch or something similar...

So I would recommend that you work on Jessie. It's what the new appliance will be for anyway (assuming that this is for Odoo)...

**Comment by l-arnold** [comment] 2015-05-26 05:37
I was working with Jessie.  Removed the package call for postgresql-9-1-postgis and it generally installed.

Was doing this to test if I could drop a TKLBAM Bu onto a Standard Lapp.  (half worked, see other issues)

**Comment by JedMeister** [comment] 2015-05-27 02:15
Hmm. I'll have to look into this further. I'm 99.999% sure that it builds for me ok... I'll double check.

**Comment by l-arnold** [comment] 2015-05-27 02:23
Issue is this call  (search for it in the repo)
'postgresql-9.1-postgis'

which is only built for wheezy so far.
see;  http://trac.osgeo.org/postgis/wiki/UsersWikiInstall

**Comment by JedMeister** [comment] 2015-05-27 02:34
Thanks. I just had a quick look and its the package name. pgsql is v9.4 in Jessie.

Have a look here: https://packages.debian.org/search?suite=jessie&section=all&arch=any&searchon=names&keywords=postgis

**Comment by l-arnold** [comment] 2015-05-27 02:38
thanks for that.  I guess I was looking at the Wiki thinking that was the full word on PostGIS.

good to keep that in.  I would assume Postgres is awesome for GIS work.  It is a very fast Database imho.

**Comment by l-arnold** [comment] 2015-05-27 02:38
Close as appropo

**Comment by DocCyblade** [comment] 2015-05-30 23:02
the lapp appliance builds fine, the issue is with the postgres appliance, and I submitted a pull request for that error.

**Comment by JedMeister** [comment] 2015-05-31 01:09
My bad. I tagged this wrong... Seeing as this & #383 are duplicates, I'm shutting this now. The other one we'll shut when the fix is merged...

**Closed by JedMeister** 2015-05-31 01:09 UTC
Labels: bug, build, postgresql
