### ISSUE TITLE
OpenVPN server restart

### ISSUE THREAD

**Issue by chariga** [turnkeylinux/tracker#752] opened 2017-01-12 21:23 UTC
Hi,

our OpenVPN server restart every hour :(
I runned apt-get update and nothing changed.

Please help.

Best regards,

Chris HARIGA

**Comment by JedMeister** [comment] 2017-01-13 02:17
Hi @chariga,

Firstly, this is our issue tracker for bugs and feature requests. Whilst your issue may be caused by some sort of bug; to be honest, it sounds more like something specific to your scenario. In my experience, unrequested automatic Linux reboots are usually caused by hardware issues, driver incompatibility or some other unexpected hardware/software misbehaviour.

I.e. it seems like something might be wrong with your system itself, as opposed to a specific bug that we can fix within the TurnKey build code. As a general rule, a bug can be easily reproduced by following a specific set of steps and this doesn't sound to me like the sort of behaviour I can make my server do.

So that makes your post more a "support request" rather than a "bug report". So it's best to create a new thread on our [support forums](https://www.turnkeylinux.org/forum/support). In your new thread, please provide as much detail as possible. Including things like:

- TurnKey appliance version
  - if you are not sure, please post the output of `turnkey-version`
- Where your appliance is running
  - e.g. VirtualBox VM or AWS EC2 or whatever
- The resources your server has or the AWS instance size (whichever seems the most relevant)
  - e.g. 1 CPU core and 2GB RAM or t2.micro
- Details of the issue with as much info as possible
  - e.g. what you've already noted ("restarts every hour") but you haven't noted whether that is consistently all day, every day; or whether it is more common at certain times, under certain load (does it always happen when people are logged in and using it, or only when it's sitting idle or whenever)
- Details of what you have tried so far
  - e.g. you note that you've run `apt-get update`. FWIW all that does is update the list of available software, it doesn't actually install anything.
- Details of other things you've checked
  - e.g. system log directly after a restart
- Any logs or error messages which you think may be relevant
  - in this case probably your current syslog (`/var/log/syslog`) and/or perhaps your previous syslog (`/var/log/syslog.1`).

---

To give you a quick pointer towards gaining better understanding of your issue, I recommend looking through your syslog files and hopefully that might highlight what is happening just before the crash. The syslog entries are time stamped so assuming you know what time the last crash was, you should be able to find it in there. Hint, to read the older syslog files (that have been archived) use the `zcat` tool. E.g.: `zcat /var/log/syslog.2.gz`.

So I'll see you on the forums once you repost there and I'll close this for now. Once you've done some more trouble shooting and it turns out that you are indeed hitting a TurnKey bug, then we can reopen this issue, or perhaps just open a new one with the details on how the bug can be reproduced.

**Closed by JedMeister** 2017-01-13 02:17 UTC
