### ISSUE TITLE
Letsencrypt certificate not trusted

### ISSUE THREAD

**Issue by chrismhinds** [turnkeylinux/tracker#678] opened 2016-07-28 14:42 UTC
Hi - I'm having an issue integrating letsencrypt with Turnkey Linux.  Before you mark this as duplicate, please note that I have already attempted to follow the existing workaround documented here: https://github.com/turnkeylinux/tracker/issues/382#issuecomment-217766799 .

When accessing my website from a desktop, it recognizes my SSL certificate.  However, when accessing via Chrome on Android, it does not recognize the certificate.

I have followed the instructions at https://github.com/turnkeylinux/tracker/issues/382#issuecomment-217766799, and my current configuration is this:

contents of /etc/ssl/private:

```
lrwxrwxrwx 1 root root       45 Jul 26 20:55 cert.key -> /etc/letsencrypt/live/$DOMAIN/privkey.pem
-r-------- 1 root root     1708 Jul 26 16:57 cert.key~
lrwxrwxrwx 1 root root       17 Jul 26 21:09 cert.pem -> cert_combined.pem
-r-------- 1 root root     3092 Jul 26 16:57 cert.pem~
lrwxrwxrwx 1 root root       43 Jul 26 20:56 cert_chain.pem -> /etc/letsencrypt/live/$DOMAIN/chain.pem
-rw-r--r-- 1 root root     3759 Jul 26 21:04 cert_combined.pem
-r-------- 1 root root      245 Jul 26 16:57 dhparams.pem
```

the cert_combined.pem file has:

```
-----BEGIN CERTIFICATE-----
[stuff]
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
[stuff]
-----END PRIVATE KEY-----
-----BEGIN DH PARAMETERS-----
[stuff]
-----END DH PARAMETERS-----
```

snippet of /etc/apache2/sites-enabled/default-ssl.conf:

```
                SSLCertificateFile      /etc/ssl/private/cert.pem
                SSLCertificateKeyFile /etc/ssl/private/cert.key
                SSLCertificateChainFile /etc/ssl/private/cert_chain.pem
```

https://www.ssllabs.com/ssltest/analyze.html?d=$DOMAIN.com shows:

```
This server supports weak Diffie-Hellman (DH) key exchange parameters. Grade capped to B.   MORE INFO »
This server's certificate chain is incomplete. Grade capped to B. 
Forward Secrecy     Weak key exchange   WEAK
```

Suggestions?

Thanks!

**Comment by JedMeister** [comment] 2016-07-29 05:26
Initially I thought that it sounds more like a bug in your Android Chrome browser (not supporting Let's Encrypt certificates) than anything else. 

If it works as it should on your desktop (double check in "Incognito" made) and SSL Labs doesn't complain about a self signed certificate, then it sounds very much like everything is configured correctly. If that's the case then there isn't much you can do about it from the server side (other than buy a "premium" certificate - which should be supported).

So out of interest I did a quick google and it seems that it is indeed a fairly common Android/Chrome issue. It seems that the required server side config is slightly different for older OS (Android,. WindowsXP, etc). I'm not sure if your Android falls into that space but it sounds possible.

TBH I'm yet to play with Let's Encrypt certs but I suggest that you go straight to the source and consult the Let's Encrypt docs. [This page](http://letsencrypt.readthedocs.io/en/latest/using.html#where-are-my-certificates) mentions required setup for different webservers. That may be able to help you out directly, although if you are unsure, then tell me the appliance and version (output of `turnkey-version`).

**Comment by JedMeister** [comment] 2017-07-27 07:41
Hi @chrismhinds - did you ever have any joy with this? I'm tempted to close it as I haven't heard back. But thought I might just ping you in case.

**Comment by chrismhinds** [comment] 2017-07-27 16:26
Thanks for the ping.  I switched to another hosting provider, and that "fixed" the error.  "Fixed" is in quotes because that doesn't fully identify the cause - which is unfortunate if you're the owner of the project and want to fix it fully.  I cannot reproduce the error again due to the new provider, so please feel free to close this.

**Comment by JedMeister** [comment] 2017-07-27 22:09
Ok thanks. Glad to hear it's "fixed" for you at least. I'll close this for now, but if you (or anyone else) encounters this again, we can reopen and try to work out what the cause is.

**Closed by JedMeister** 2017-07-27 22:09 UTC
Labels: bug
