### ISSUE TITLE
Trac - on proxmox, admin password is stored incorrectly with turnkey-init

### ISSUE THREAD

**Issue by genewitch** [turnkeylinux/tracker#1500] opened 2020-08-01 12:51 UTC
the password is stored in /etc/trac/htpasswd and using htpasswd -v htpasswd admin and putting in the password that i typed into turnkey-init says "verification failed" - resetting the password with htpasswd htpasswd admin allows me to log in to the trac page.

hope this makes sense, the turnkey-init is using an incorrect option or something.

**Comment by genewitch** [comment] 2020-08-01 13:01
sorry, this needs to be tagged "Trac" but i don't remember how.

**Comment by JedMeister** [comment] 2020-08-02 21:56
Thanks for the bug report. I've added the tags (only "admins" can do that). :smile:

**Comment by OnGle** [comment] 2020-11-18 04:52
I was unable to reproduce this issue either via proxmox 16.0 container, or a 16.0 fresh build from chroot on tkldev. I'm going to close this issue for the time being, if anybody **can** re-produce this issue and has more information feel free to re-open or post here and we'll address it

**Closed by OnGle** 2020-11-18 04:52 UTC
Labels: bug, trac
