### ISSUE TITLE
Typo in turnkey-init causes script to halt prematurely

### ISSUE THREAD

**Issue by fredmenez** [turnkeylinux/tracker#1451] opened 2020-05-10 23:02 UTC
Seen when using `debian-10-turnkey-nextcloud_16.0-1_amd64.tar.gz` in proxmox LXC container, `turnkey-init` displays an error : confconsole complains about incorrect arg :

&rarr; https://github.com/turnkeylinux/inithooks/blob/9bb5dc11fc7a7948dc587851d58c078569207ae2/turnkey-init#L95

**Comment by JedMeister** [comment] 2020-05-10 23:25
Thanks for reporting @fredmenez - argh! TBH, I'm not sure how I managed to miss that in my testing...

Looking a bit closer, I don't think that line should still be there at all! The lines before it should be setting the `confconsole` command appropriately.

**Comment by fredmenez** [comment] 2020-05-10 23:39
Hi @JedMeister, thanks for taking notice. A little bit of context : the configuration console did run until the step "do you want to install updates", and then apt started running and after that the error regarding --useage popped up.

Being new to turnkey linux i couldn't devise whether this was a significant error.

All i know is that after leaving the console `netstat -tulpn` wasn't showing any process listening on the port mentioned in the console; nor was `ps aux` displaying any of the expected services (mariadb, redis...) to be running.

**Comment by JedMeister** [comment] 2020-05-11 00:52
@fredmenez - Thanks for the extra info. FYI, it's not a significant error, but is a bit untidy. It means that instead of launching our "Configuration console" (aka `confconsole`) when inithooks is done, it unceremoniously dumps the user back to the commandline at the end of the inithooks run.

In an effort to try to explain what is going on (and why it's not really that significant):

As you are aware, the script that's running when this occurs is called "inithooks" (short for "initialization hooks") and is primarily used for first boot initialization (such as setting passwords etc). It actually runs on every boot though (although IIRC there is nothing configured to run every boot on a LXC container by default). The line that is causing the issue is right at the end of it's run.

By design, when it finishes running it hands over to Confconsole. Confconsole is a tool designed to allow users to easily configure a number of different components. It has 2 levels of functionality; one is designed for if the user is already logged in and provides a range of menus to configure a number of settings. The other has limited functionality and basically just displays some IP information. This second "limited" functionality requires the (poorly named) `--usage` switch (FWIW I plan to deprecate that misleading switch name at some point ASAP).

The line that you pointed out shouldn't have actually still been there. The [preceding lines](https://github.com/turnkeylinux/inithooks/blob/9bb5dc11fc7a7948dc587851d58c078569207ae2/turnkey-init#L87-L92) should construct the command to run (either `['/usr/bin/confconsole', '--usage']` if confconsole exists, or otherwise `['/bin/true', '--null']`). This will make `turnkey-init` default to just showing the limited info.

For some further context on why this change has been introduced (probably of more value to existing TurnKey users): In previous TurnKey versions, Confconsole used to run as it's own service, but as systemd (the system initialisation component that manages services) gets better at running everything asynchronously (and starting things concurrently) this has cuased issues with inithooks and confconsole fighting each other for control (rather than inithooks running first, then confconsole starting afterwards). So to resolve that in v16.0, we simply removed the confconsole service and launched it as the final step of inithooks.

The part of the code that includes the typo (which you discovered) won't cause any significant issue as it occurs right at the end ([this line](https://github.com/turnkeylinux/inithooks/blob/9bb5dc11fc7a7948dc587851d58c078569207ae2/turnkey-init#L106)), when it exits. It just means that you will get dumped back to the commandline , with a error message rather than seeing the confconsole IP info.

**Comment by fredmenez** [comment] 2020-05-11 00:58
Thanks for the comprehensive explanation @JedMeister !

This is OT but where would direct me to find out why the nextcloud dependency services i was expecting to see running weren't running (mariadb, redis, nginx or apache) ?

Have a good day

**Comment by JedMeister** [comment] 2020-05-11 01:04
Closed by: https://github.com/turnkeylinux/inithooks/commit/cc3c8db323b8c22bf3593e15f43504dec841074a

Updated package version: `2.0.1+5+gcc3c8db`.

----

To update:

```
apt update
apt install inithooks
```
To double check that you have the latest package:
```
apt policy inithooks
```
Should output this:
```
inithooks:
  Installed: 2.0.1+5+gcc3c8db
  Candidate: 2.0.1+5+gcc3c8db
  Version table:
 *** 2.0.1+5+gcc3c8db 999
        999 http://archive.turnkeylinux.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Closed by JedMeister** 2020-05-11 01:04 UTC
Labels: bug, inithooks

**Comment by JedMeister** [comment] 2020-05-11 01:11
FWIW, as a general rule, we prefer support related questions via our [forums](https://www.turnkeylinux.org/forum) (new threads require a free website user account).

But seeing as we're already here...

> This is OT but where would direct me to find out why the nextcloud dependency services i was expecting to see running weren't running (mariadb, redis, nginx or apache) ?

Where are you looking for them? Via sommandline you should find them like this:
```
systemctl status apache2
systemctl status mysql
systemctl status redis # TBH, I forget if Nextcloud has redis by default?
