### ISSUE TITLE
(Jessie) TKLDEV-Jessie  (lapp did not build)

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#336] opened 2015-05-08 18:47 UTC
TKLDEVRC1 from Mirror/turnkeylinux Core builds OK.
Lapp not quite.

L. Arnold - Fri, 2015/05/08 - 12:44.
seemed close but we got to here:

touch:  cannot touch '/etc/apache2/conf.d/phppgadmin' No such file or directory

/usr/share/fab/product.mk:476  : recipe for target 'build/stamps/root.patched' failed

Error 1

Likely Lapp has not caught up with Core with different build schemes but not sure the situation.

—

**Comment by l-arnold** [comment] 2015-05-08 19:13
Do all the Steps for Manual Setup need to be applied?
in https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/setup.rst

It appears that a Recent Change is hovering aroiund this here:

https://github.com/turnkeylinux/common

"adjusted apache2 phppgadmin site symlink to adhere to Jessie's strict…"

**Comment by l-arnold** [comment] 2015-05-08 19:19
Do all the Steps for TKLDEV Manual Setup need to be applied?
in https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/setup.rst
ie: Bootstrap (not clear what to do there)
CD Root  (seems in but?)
Common (seems in but?)

**Comment by l-arnold** [comment] 2015-05-10 00:11
Testing a few variants.  Able to get TKLDEVS to build in 32 Bit versions but not in 64 Bit versions.
Seems there are some package movements in Wheezy 64 bit, possibly in advance of Jessie.

Verified issues both in VM implementations and AWS Implementations.

**Comment by l-arnold** [comment] 2015-05-10 00:23
In Wheezy, both 32 and 64 Bit getting the error with apt-get update
"There is no public key available for the following key ID's"
(then lists an id)
"There is no public key available for the following key ID's"
(then lists a second id)

AWS is not building with Wheezy.
32 Bit Wheezy on VM is Building the same image complete.

**Comment by l-arnold** [comment] 2015-05-10 00:35
Not sure if this is devolving:  Error reads in AWS 32 Bit Wheezy

"unable to locate package isolinux"

Not really understanding, but Debian 
https://packages.debian.org/sid/all/syslinux-common/filelist
says  should be something like here (not really talking about Generations)
/usr/share/doc/syslinux-common/asciidoc/isolinux.txt.gz

**Comment by JedMeister** [comment] 2015-05-10 01:04
Wheezy should still work ok, but you'll need to use the version tags to download the older version of the repo.

The V14.0/Wheezy update is work in progress. It is probably best if you report each issue you come across with the Jessie build individually (i.e. make a new issue) and as explicitly as possible. As much as possible explain what you were doing and what the out come was; i.e. how to reproduce the issue. Feel free to speculate on the cause and/or what you tried to do (if anything) to fix it...

**Comment by JedMeister** [comment] 2015-05-10 13:16
@l-arnold - I've just fixed common so that Jessie LAPP builds. I haven't tested any further than that yet though. Until it's merged with the official TKL branch though you're probably better of using my fork.

Here's how:
````
cd /turnkey/fab
mv common common.orig
git clone -b jessie-apache-tweak https://github.com/JedMeister/common.git
#assuming that you already have lapp cloned
cd ../products/lapp
make clean && make
````

**Comment by l-arnold** [comment] 2015-05-10 15:16
Helpful.

I've gotten some 386 wheeze Odoo to build.
let's try 64 Bit Jessie.

thank you for all your help and support

Sent from Nine

**Comment by JedMeister** [comment] 2015-05-11 02:58
I have fixed this in my common repo, but I'll leave this bug open for now until the changes are merged into TKL common...

**Comment by JedMeister** [comment] 2015-05-17 06:28
I am closing this issue as some changes to LAPP have been merged into common - enough so that LAPP builds ok now.

Please feel free to reopen this issue (or open a new one) if it's relevant. Thanks :smile:

**Closed by JedMeister** 2015-05-17 06:28 UTC
Labels: bug, lapp
