### ISSUE TITLE
ZurmoCRM: All queries are redirected to www.example.com

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#834] opened 2017-05-15 18:27 UTC
When installing Zurmo as an LXC container, the application installation defaults to www.example.com, with the result that all queries to the webpage get redirected to www.example.com/...
I tried to override this behavior by setting the domain in inithooks.conf, but it had no effect. I believe the correct behavior would be to use the hostname "zurmo" and the domain from inithooks.conf, e.g. something like zurmo.local.lxc.

**Comment by JedMeister** [comment] 2017-08-09 02:37
The domain inithook should certainly change it so that it redirects to the new domain (and not example.com). 

This really should have been fixed in v14.2, but unfortunately it got missed because I've been focusing on the issues tagged to the v14.2 milestone (and this one wasn't). Pinning to v15.0 milestone now so it doesn't get forgotten.

**Comment by OnGle** [comment] 2018-03-05 00:35
Was unable to reproduce this in root.patched. Just about to double check it built to LXC

**Comment by Dude4Linux** [comment] 2018-03-05 15:05
@OnGle @JedMeister While I was working on converting root.patched into an lxc2 (lxd) image, I think I discovered a serious flaw in the lxc-turnkey template.  I've always known that the LXC appliance won't run in a nested container, but never figured out why.  I believe I read a report that OpenVPN won't run in a container and I'm sure there must be others that are not fully functional when running in a container. I don't know if Zurmo is one of these, but it certainly a possibility, especially if it runs in a VM.

I'm working on a strategy to deal with the flaw now and will let you know when the fix is available. The strategy is to examine the /etc/network/interfaces file and adjust the container config appropriately.

**Comment by JedMeister** [comment] 2018-03-05 20:48
@Dude4Linux - AFAIK the primary issue with running nested containers is to do with the way that "union" filesystems (e.g. auFS, OverlayFS, etc) work. Generally they only allow a set number of layers and within that, only a subset of writeable layers. As a container is generally already running on a layer of union FS itself, adding additional writeable layers to that can cause issues. 

The OpenVPN issue is completely separate and is to do with expected devices not being available. See https://github.com/turnkeylinux/tracker/issues/1011

**Comment by OnGle** [comment] 2018-03-07 01:00
@Dude4Linux I've done a fair bit of testing and am unable to reproduce this issue. I was having some intermittant issues with redirection but that appears to be purely due to browser dns caching not honoring my `/etc/hosts`, after realizing this I proceeded to test using lynx and was unable to find any issues at all relating to incorrect redirection. A couple of things which spring to mind as potential causes are LXC host dns caching, other caching that may be occuring within your test environment, zurmo bugs present in the 14.2 release,  preseeding bugs present in 14.2 or perhaps a bug in the 14.2 inithook itself.

In any case I suggest we close this issue as it seems to no longer occur in an up-to-date tkl installation, feel free to reopen if you can re-produce this issue using more recent turnkey versions.

**Closed by OnGle** 2018-03-07 01:00 UTC
Labels: bug, zurmo
