### ISSUE TITLE
TCP port 10000

### ISSUE THREAD

**Issue by prassaschr** [turnkeylinux/tracker#745] opened 2016-12-05 14:16 UTC
Hi,
If I use TCP port 10000 for any service , like for example openvpn, after that, I can't access the 12321 main control (webmin). I believe that you must restrict the use of the 10000 tcp port.

**Comment by JedMeister** [comment] 2016-12-12 23:34
Hi apologies for delayed response.

Your experience is expected behaviour. That is because Webmin uses both port 10000 (internally) and port 12321 (externally via stunnel).

To avoid the issue you are experiencing, either don't use port 10000 or reassign Webmin to listen on an alternate port internally and adjust the stunnel configuration link the internal port to the external port.

**Closed by JedMeister** 2016-12-12 23:34 UTC
Labels: won't fix, workaround
