### ISSUE TITLE
Google Search Returns for Forum Posts - returning Error when clicked

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#394] opened 2015-06-10 19:49 UTC
Using Chrome

Google Search:  samba setup why does root folder show in the storage tree turnkeylinux

returned:
https://www.turnkeylinux.org/forum/support/20131011/samba-shares-have-root-owner-no-one-else-can-write-them

When selected:

This webpage is not available

ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Detail says:
A secure connection cannot be established because this site uses an unsupported protocol.

removing "s" in "https" gets it to work.  I know Google is wanting https as prefered method so something is up there.

**Comment by JedMeister** [comment] 2015-06-11 01:54
What web browser? Have you tried other web browsers? Clearing cache and cookies and restarting your browser?

I can't reproduce this. I'm using Google Chrome Version 43.0.2357.81 (64-bit) on Debian Wheezy

**Comment by l-arnold** [comment] 2015-06-11 02:39
Chrome  (will run the update it is recommending)

Version 43.0.2357.81 m
 
Nearly up-to-date! Relaunch Google Chrome to finish updating.

**Comment by l-arnold** [comment] 2015-06-11 02:46
Repeats after update.  I will try from a different machine and also browser.

**Comment by JedMeister** [comment] 2015-06-11 03:33
Hmm, strange. Definitely working here... Perhaps try a different browser too and/or clean your cache and cookies. I often use 'private/incognito' mode to test stuff like that too (when in 'private/incognito' mode it uses a clean cache and no existing cookies).

I'll get some others to test it too.

**Comment by l-arnold** [comment] 2015-06-12 01:32
Same result on a second machine in Chrome.
Google Search:  "turnkeylinux postfix"  first return is 
https://www.turnkeylinux.org/forum/tags/postfix

Firefox did not give an error on the 2nd machine. Internet Explorer did as it did on the first machine.
both are inside my router (little firewall).  Comcast is the DNS provider.

I also checked Firefox on the first machine and it was also fine (worked).

Google does give the result, but Chrome will not open the page:  Details say:
This webpage is not available

ERR_SSL_VERSION_OR_CIPHER_MISMATCH
Hide details
A secure connection cannot be established because this site uses an unsupported protocol.

**Comment by l-arnold** [comment] 2015-06-12 01:35
Searched with Bing with Chrome on Computer #.
Got a different Return from the search
but same result.  (cipher mismatch)

**Comment by JedMeister** [comment] 2015-06-12 01:58
Ok thanks Landis. I can't reproduce the issue and from my research there are ways to work around it (it seems possible that the https TurnKey site is using a cipher to encode the traffic which chrome & IE can't handle by default - the site uses TLS 1.1 so that shouldn't be an issue). 

But the fact that you can reproduce the issue on different PCs is enough for me... I will ping Liraz and let him know.

Even if just for the time being we disable https would do. Better to lose some google page ranks (but not using https) and people be able to see our site, than not be able to see it at all...

**Comment by JedMeister** [comment] 2015-10-20 23:55
Closing as this should now be fixed. Please reopen if you have further issues.

**Closed by JedMeister** 2015-10-20 23:55 UTC
Labels: bug, website
