### ISSUE TITLE
ssh keyauth not working for all openstack images based on core >=15

### ISSUE THREAD

**Issue by kaergel** [turnkeylinux/tracker#1318] opened 2019-04-03 13:20 UTC
Hi,

it looks like the ssh-publickey does not get properly injected in the own- and nextcloud openstack images with version >=15. No login is possible. I've tested the following images:

- turnkey-nextcloud-15.0-stretch-amd64-openstack.qcow2   
- turnkey-nextcloud-15.1-stretch-amd64-openstack.qcow2   
- turnkey-owncloud-15.0-stretch-amd64-openstack.qcow2  
- turnkey-owncloud-15.1-stretch-amd64-openstack.qcow2   

`ssh root@<floatingip>`  does not work and asks for password. Nextcloud 14.2 is working.

Best regards

**Comment by JedMeister** [comment] 2019-04-03 19:57
Hi @kaergel 

Could you please tell me where/how you are launching this appliance? Also if it's on AWS (via Hub or Marketplace) which region you are using.

**Comment by kaergel** [comment] 2019-04-04 09:27
Hi, it's a private Openstack cloud. Based on Openstack Qeens release.  My method was:

- upload the image with --disk-format qcow2 --container-format bare --public --property os_type=linux
- create a suitable flavor i.e. `openstack flavor create --id 7 --ram 4096 --disk 1 --vcpus 3 myflavor`
- deploy an instance on cinder-volume with 20GB
- associate a floating ip
- select the ssh-keypair and start deploying

After that the instance was successfully created it can be accessed from the outside via it's floatingIP. This works for:

- turnkey-nextcloud-14.2-jessie-amd64-openstack.qcow2

You now can login via `ssh root@<floatingip>` and perform the initial setup. This method does not work for all own-/nextcloud images >=15 mentioned in my first post.

**Comment by JedMeister** [comment] 2019-04-04 21:14
Ok, thanks for the additional info, Unfortunately I don't have access to OpenStack, but we did have a hosting provider which uses OpenStack test them out when we were developing v15.0, so I'm not sure what has gone wrong since then?

It's strange that the v14.x ones are working for you, but not v15.x. Whilst they are based on different versions of Debian (v14.x = Debian 8/Jessie; v15.x = Debian 9/Stretch) the key handling shouldn't be any different?! Especially if OpenStack is injecting the public key into `/root/.ssh/authorized_keys` as I assume it is?!

The only thing that does occur to me is that in v15.x we have implemented 2 changes which may be factors in this. One is hardening of default SSH config, the other is the introduction of fail2ban by default. I wonder if it's either or both of these things that are contributing to the issue? 

Assuming that you are trying to connect from a Linux machine, can you please try increasing the verbosity of ssh when you try to connect and share that. I.e.

```
ssh -v root@<floatingip>
```
You can also increase the verbosity by adding more 'v's (up to a total of 3 AFAIK).

If you are using something else to connect, hopefully it also has a way of providing more info.

**Comment by JedMeister** [comment] 2019-04-04 21:27
What might also assist troubleshooting this is logging in via the randomly generated password. You should be able to read it from the logs the very first time the image boots.

Then you can check to ensure that your public key is properly in place (in `/root/.ssh/authorized_keys`).

You can also try adjusting the number of SSH login retries (`MaxAuthTries` - current default is 2; I suggest upping that to 3) and see if that helps.

And one other thing you can test out, is stopping fail2ban (I suggest just temporarily - for testing, but that's your call).
If you just want to stop it (will reload on reboot; or manually restart using the `start` command):

```
service fail2ban stop
# or
systemctl stop fail2ban
```
To disable it altogether:
```
systemctl disable fail2ban
```

**Comment by kaergel** [comment] 2019-04-16 09:03
I did some more testing and this are the results:

The problem does also seem to exist on turnkey-core-15.0, so it's not related specifically to next-/owncloud images. I did capture bootloogs from all discussed images and attached them to this post. I did also capture the output of `ssh -v root@<floatingip>`.
The thing i recognized is that there's no output regarding inithooks for images based on core =>15. Looks like they`re not run at all. I went ahead an mounted one the instance disks and took a look inside the filesystem  and there is no logfile at /var/log/inithooks.log, no files at all in /root/.ssh at all and so on...

[bootlog_core_14.2.txt](https://github.com/turnkeylinux/tracker/files/3083907/bootlog_core_14.2.txt)
[bootlog_core_15.0.txt](https://github.com/turnkeylinux/tracker/files/3083908/bootlog_core_15.0.txt)
[bootlog_nextcloud_14.2.txt](https://github.com/turnkeylinux/tracker/files/3083916/bootlog_nextcloud_14.2.txt)
[bootlog_nextcloud_15.1.txt](https://github.com/turnkeylinux/tracker/files/3083917/bootlog_nextcloud_15.1.txt)
[bootlog_owncloud_15.1.txt](https://github.com/turnkeylinux/tracker/files/3083918/bootlog_owncloud_15.1.txt)

[sshlog_nextcloud_14.2.txt](https://github.com/turnkeylinux/tracker/files/3083960/sshlog_nextcloud_14.2.txt)
[sshlog_nextcloud_15.1.txt](https://github.com/turnkeylinux/tracker/files/3083961/sshlog_nextcloud_15.1.txt)

If want to test this on Openstack yourself you can also use a openstack-development-environment like "Devstack" https://docs.openstack.org/devstack/latest/.

**Comment by kaergel** [comment] 2019-04-18 14:05
changed title because all images based on core >=15 seem to be affected

**Comment by mpetrowi** [comment] 2019-11-14 16:43
I think this is related to this bug report.   Please consider removing   "MaxAuthTries 2" from sshd_config.

I have 2 public keys and it took me an hour to figure out why ssh as root was failing due to "Too many authentication failures".  (Complicating the fact was Virtual box networking weirdness.) Then when I figured out MaxAuthTries, fail2ban had already kicked in and I had to sort that out.  I'm a new turnkey user and this made for a rough start.  sshd default configuration and fail2ban should be more than sufficient without this setting.

**Comment by JedMeister** [comment] 2019-11-14 19:16
Hi @mpetrowi,

Sorry to hear of your troubles. It certainly doesn't sound like you had a very "TurnKey" experience... :cry: We try to balance good security defaults against ease of use as best we can, and clearly we sometimes get it wrong...

Regardless, thanks for bringing this bug report back to my attention. FWIW, I'm almost certain that the cause of this specific bug on OpenStack was directly related to #1340 (which was resolved a few months ago by fixing the specific issue and rebuilding all the OpenStack builds). @kaergel - sorry for not being proactive and letting you know sooner! Hopefully better late than never...

However @mpetrowi, your point is a good one. We implemented `MaxAuthTries 2` for v15.x on the recommendation of a very security conscious community member. Fail2ban was also implemented around the same time and having it that tight alongside fail2ban was/is probably overkill. Beyond your scenario, `MaxAuthTries 2` also means that `ssh-copy-id` doesn't work out of the box either (see #1130).

As per the closure of that issue, we've bumped [`MaxAuthTries` to 3](https://github.com/turnkeylinux/common/commit/f8a37c85621d262099a4558531a6dc98db517628) for our next major release (v16.0 - unfortunately, it will still be a little while away, but getting closer...). IIRC the default is 6, but as we allow password logins (to make life easier for new users; default is to accept keys only), it's important to lock it down a little more IMO.

For future reference, (assuming that you are using OpenSSH client) I found the best way to discover the cause of the issue when trying to log in via SSH is to launch `ssh` with the `-vvv` switch. In my case that made it pretty clear what was going on... It's perhaps also worth noting, that using the `-o PubkeyAuthentication=no` switch should force your OpenSSH client to not try any keys and just ask for a password.

I'll close this now, but as a "new to TurnKey user" @mpetrowi, we really value your input. So if you have any further suggestions, please feel free to share. Although, unless it's directly related to my post here; ideally please do that on a directly relevant issue, or over on our [forums](https://www.turnkeylinux.org/forum) (requires free website user account).

**Closed by JedMeister** 2019-11-14 19:16 UTC
Labels: bug, openstack (build type)

**Comment by mpetrowi** [comment] 2019-11-14 20:10
Hi @JedMeister   Thanks for the response and sorry about tacking this on the wrong issue.  I am impressed with turnkey so far, at least once I got past the not being able to login part.  Cheers!

**Comment by JedMeister** [comment] 2019-11-14 22:06
@mpetrowi:

> Thanks for the response

You're most welcome. It's the least that I could do considering that you're giving us feedback on how we could do better! :smile: 

> sorry about tacking this on the wrong issue

No problem! It was good actually as this issue needed closing anyway. Besides, we're fairly casual about that stuff. It's better to have the feedback in a place that's not ideal, rather than not at all! :smile: 

> I am impressed with turnkey so far, at least once I got past the not being able to login part.

Glad to hear (other than than the not being able to log in part...).

As I say though, if you have any other further thoughts to share, please do so. Here on our GitHub issue tracker is the place for bug reports and feature requests (either post in the most appropriate existing issue if there is one, or post in a "new issue" and we'll respond and tag it as appropriate). On the forums is the place for more general feedback and/or support.

Have a good one and hope that TurnKey works well for you.

**Comment by MichaelJCole** [comment] 2020-04-05 17:50
@JedMeister  Does this mean I have to delete keys from ~/.ssh for this to work?  I have 4 there.  This seems like a landmine for new users.

**Comment by JedMeister** [comment] 2020-04-06 00:36
@MichaelJCole - FWIW I just replied to your [forum post](https://www.turnkeylinux.org/forum/general/sun-20200405-2152/getting-ass-kicked-digitalocean#comment-47963) (assuming that you're the same Michael Cole?! :smile: ).

Depending on what OS you're on and/or which SSH client you're using, it should be possible to explicitly note the key you wish to present for authentication. E.g. to use `~/.ssh/this_key` on Linux (OpenSSH):
```
ssh -i ~/.ssh/this_key root@your_server.example.com
```
FWIW, if you have a domain assigned to the server, then it's also possible to set this up for all future logins too in `~/.ssh/config` - e.g.:
```
Host your_server.example.com
  User root
  IdentityFile ~/.ssh/this_key
```
Then you can just log in:
```
ssh your_server.example.com
```
Anyway, I digress...
> This seems like a landmine for new users.

Yep, hence why we've changed it for our upcoming next release (to 3); although it will still fail with 4 keys...

**Comment by MichaelJCole** [comment] 2020-04-06 17:21
@JedMeister Yes!  Thank you!  I should have thought of that :-)
