### ISSUE TITLE
YouPHPTube LetsEncrypt fails from Confconsole

### ISSUE THREAD

**Issue by walt93** [turnkeylinux/tracker#1382] opened 2019-11-17 10:42 UTC
Fails with error

+ ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org'/acme/new-reg (Status 400)
Details:
{
 "type": "urn:acme:error:badNonce",
 "detail": "JWS has no anti-replay nonce",

Then, the terminal UX cuts off the rest of the error with a useless "55%" indicator (and how the @@@@ do you scroll this @@@@ing thing?)

**Comment by JedMeister** [comment] 2019-11-17 20:07
Hi @walt93 - This looks like a duplicate of #1359 so I'll close this one for now.

To resolve it, please follow the steps as outlined in the [Confconsole v1.1.1 release notes](https://github.com/turnkeylinux/confconsole/releases/tag/v1.1.1). If you have any troubles, you can post back here if you'd like and I'll see it and respond.

Re scrolling, try the PageDown key (sometimes displayed as 'PgDn' on some keyboards). (and PageUp to go back up again). FWIW, that output also goes to the log (I forget the exact path OTTOMH, but it should be something like `/var/log/confconsole/letsencrypt.log` or similar).

**Closed by JedMeister** 2019-11-17 20:07 UTC
Labels: core, duplicate, youphptube
