### ISSUE TITLE
when creating a container for openvz - ip address for venet0:0 is not detected correctly - finds 127.0.0.2

### ISSUE THREAD

**Issue by fiveways** [turnkeylinux/tracker#700] opened 2016-09-08 09:22 UTC
Hi Team,
when creating a container for openvz - ip address for venet0:0 is not detected correctly - finds 127.0.0.2

Just started playing with tlk templates with openvz and noticed some templates believe the ip address of the container is 127.0.0.2

Happy for the templates to use the first ip on venet0:0, happy to do testing and provide patches, just not sure where to start.

**Comment by qrntz** [comment] 2016-09-11 20:47
Could you please provide some details about your environment?

I would like to know which OS you are running as the OpenVZ host, the version of vzctl and network configuration (bridged or routed). Please also copy&paste the output of those commands executed on the affected VM:
```console
cat /etc/hosts
```
```console
ifconfig -a
```

**Comment by JedMeister** [comment] 2016-09-11 23:04
As the name suggests, our current "Proxmox" build is optimised for ProxmoxVE (which uses LXC as of v4.0). However I did test them on Proxmox v3.4 (which uses OVZ) and they worked OOTB. Having said that, ideally if we can better support vanilla OVZ without compromising support for LXC/Proxmox support then we should do it. If you can answer @qrntz's questions then we may be able to do that better, or at least make it work a little nicer (i.e. document a workaround, etc).

**Comment by JedMeister** [comment] 2020-01-12 21:32
I'm going to close this now. OpenVZ is dead and we've been unable to reproduce this issue on LXC.

**Closed by JedMeister** 2020-01-12 21:32 UTC
Labels: container (build type), feature, ovz (build type)
