### ISSUE TITLE
password string evaluation in init .py script fault

### ISSUE THREAD

**Issue by data-director** [turnkeylinux/tracker#1293] opened 2019-01-19 06:09 UTC
There is an issue with the evaluation of the string length when using special characters in the first 7 characters for the domain administrator account password.

Exceptions were thrown during initialization script execution in regards to password length being too short.
Password exceeded length requirement, but special characters in first 7 spaces resulted in faulty evaluation.

Have not reviewed source to attempt to locate code position, but I can provide a stack trace/potential solution when I have time available.

**Comment by JedMeister** [comment] 2019-01-20 21:48
Hi, thanks for your bug report.

I haven't yet attempted to reproduce your issue, and haven't come across it myself during testing. It would be great if you could explicitly state the character(s) that caused the issue.

FWIW there are some generic password requirements provided by the base inithooks program itself (IIRC minimum length of 8 characters, containing at least 3 of the 4 groups; uppercase letters, lowercase letters, numbers, special characters.

Then the Domain-Controller inithook has additional requirements (because of the specific requirements of Samba). We discovered that some special characters are problematic with Samba (it allows the password to be set with them, but then will not allow login).

**Comment by JedMeister** [comment] 2019-01-21 04:40
I think there are a few characters that caused issue. IIRC `$` was one. Parenthesis `()` were also problematic I think.

I really appreciate you taking the time to report the issue. Thanks for that! :+1:

**Comment by OnGle** [comment] 2020-11-18 05:24
Oh this looks like one for me, let me see if this is a generic password_prompt issue in dialog wrapper

**Comment by OnGle** [comment] 2020-11-18 05:39
Ok I can't see anywhere this would be an issue in dialog_wrapper and further more some basic testing seems to confirm this is the case. So presumably this is a domain controller specific issue.

Suggested fix: passing the offending characters into ``Dialog.get_password``'s ``blacklist`` named argument:

``get_password(title, text, blacklist=['$', '(', ')'])``

**Comment by JedMeister** [comment] 2020-11-18 23:44
@OnGle - it looks like the inithook currently leverages `Dialog.get_password`'s `blacklist` - although I note that currently it's only blacklisting parenthases (i.e. `(` & `)`):

```
            admin_password = d.get_password(
                    "Samba Password",
                    "Enter password for the samba 'Administrator' account.",
                    pass_req=8, min_complexity=3, blacklist=['(', ')'])
```
(Currently that code is lines [322-325](https://github.com/turnkeylinux-apps/domain-controller/blob/master/overlay/usr/lib/inithooks/bin/domain-controller.py#L322-L325))

I suspect that the `$` may no longer be an issue now as the whole inithook is python. v15.x had bash inithooks which were called by the python, and if the quoting/escaping wasn't correct I suspect that the `$` may have got lost?

Although we need to test...

**Comment by JedMeister** [comment] 2021-05-17 06:09
I have updated the inithook a little more and have tested using `$` and it works fine now. I'm going to close this issue now.

**Closed** 2021-05-30 23:17 UTC
Labels: bug, domain-controller, inithooks
