### ISSUE TITLE
Rails: Passenger dead after after the first boot; race condition?

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#635] opened 2016-05-12 11:27 UTC
and the example Rails project is at /var/www/railsapp, not /var/www/rails, as documented. And there's not rails app inside.

**Comment by JedMeister** [comment] 2016-05-13 03:02
Thanks again for the heads up on this. I've fixed the readme and appliance page (re the example project location).

But I can't reproduce the 500 error. I get the TKL landing page (which is the "example app") on both http and https. I've tested the container and the ISO. I'm closing for now.

**Comment by vondrt4** [comment] 2016-05-17 08:42
I must insist. I've tried it now myself. I'm not using the official ISOs, but OpenStack builds made from them using Buildtasks. The modified version with cloud-init, but that should be of little consequence.

After start, Passenger was not running. Apache restart helped. Looking at the logs, it seems that systemd is restarting apache after a short while after its first start. That is due to `/usr/lib/inithooks/firstboot.d/15regen-sslcert`. Then Passenger vanished. OK, restarted Apache.

But then is started saying in `/var/log/apache2/error.log`
`Exception RuntimeError in Rack application object (Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml` and I really had to go there and set the two variables.

That is managed in `/usr/lib/inithooks/firstboot.d/20regen-rails-secrets` Ah, I see. What is this part supposed to do?
`
APPNAME=$(cat /etc/hostname)
[ "$APPNAME" == "rails" ] && APPNAME=railsapp ## namespace conflict
WEBROOT=/var/www/$APPNAME
`
Because I have just changed the hostname using cloud-init to whatever the user entered in OpenStack as instance name.

Solutions:
a) A better detection of application name is implemented..
b) I change the order of cloud-init scripts, so that hostname is changed after inithooks are run.

**Comment by JedMeister** [comment] 2016-05-17 09:03
The bodgey code that used the hostname to determine the appliance was fixed sometime ago (March 22nd to be precise):
https://github.com/turnkeylinux/common/commit/a812b73623ff57c55a5ff3e6f6fea4e6ed9f9fe9

So all v14.1 appliances should include this fix.

My guess is that your common is out of sync with our master. Does that sound likely?

**Comment by vondrt4** [comment] 2016-05-17 09:19
Hmm, my common is out of sync, yes. But buildtasks works on official ISOs, don't they?
I think there is another task to make it possible to build using TKLDev directly to another format than ISO.

**Comment by JedMeister** [comment] 2016-05-17 09:54
Ah yes, by default it should build from the existing ISO (i.e. download it and unpack it) so you're right that shouldn't be the issue. 

I have just looked a bit closer and it looks like although the commit is quite old, it was only just merged into common about a month ago and it looks like the commit didn't quite make it into v14.1. 

So my apologies on that. You are correct that the issue is still valid for v14.1 but has been fixed in common so will be included in v14.2 when we release that...

Currently there isn't a script to build directly to any of the alternate builds. But I often build to container with `./bt-iso app_name && .bt-container app_name`

**Comment by vondrt4** [comment] 2016-05-17 15:23
Thanks for the tip. Because the error is only present in my cloud-init build, I'm building rails 14.1 with the new common.

**Comment by vondrt4** [comment] 2016-05-18 16:36
There's still the thing with Passenger being dead after the first boot. I sniff some weird race condition. You may hit it with the next build. Or not.
I strongly suggest replacing the last line in `/usr/lib/inithooks/firstboot.d/20regen-rails-secrets`, which should restart passenger, by `service apache2 reload`.

**Comment by JedMeister** [comment] 2016-05-19 06:56
So you mean add `service apache2 reload` to the end of https://github.com/turnkeylinux/common/blob/master/overlays/rails/usr/lib/inithooks/firstboot.d/20regen-rails-secrets?

**Comment by vondrt4** [comment] 2016-05-19 07:33
Yes, instead of the current touch.. something that restarts passenger. I was finding the apache passenger module unable to connect to passenger core, althought it was there listening to its socket.

**Comment by JedMeister** [comment] 2016-05-19 07:47
Ok, I'll reopen this and get @qrntz to have a quick look when he gets a chance.

**Comment by JedMeister** [comment] 2016-05-19 07:49
I updated the title a little to better reflect where we've got too! :smile:

**Comment by vondrt4** [comment] 2016-05-19 08:58
Sorry, the change does not help. When I run it off a fast SAN array and with ec2 user data preseeding for inithooks, it bites me again.

**Comment by vondrt4** [comment] 2016-05-19 09:28
https://github.com/phusion/passenger/issues/1561

**Comment by vondrt4** [comment] 2016-05-19 15:09
Out of ideas. I have just tried to eliminate all apache restarts. I did `update-rc.d apache2 disable` while building the image and enable after the certificate generation inithook, and I still got two Passenger restarts at the same time in the apache error log (and no apache restarts or reloads in the systemd log).

Going for the radical solution. Enabling 99reboot. That works reliably.

**Comment by JedMeister** [comment] 2016-05-20 03:23
Hmm, sounds like something funky is going on... I wonder why none of us have hit this previously? It doesn't seem like something that would be OpenStack related. I'm inclined to suspect that you are right that it is some sort of race condition that in many/most cases doesn't get triggered, but in yours it does...

**Comment by qrntz** [comment] 2016-05-20 15:40
I'm getting a different error which is puzzling regardless. Looking into this.

**Comment by JedMeister** [comment] 2017-06-21 10:08
We'll have a v14.2 Rails app for you shortly @vondrt4 TBH we haven't explicitly resolved this issue, but we were unable to reproduce it. So I guess YMMV. Also the OpenStack builds (of the v14.2 apps built so far) are on the mirror. I'll be announcing them on the blog any day...

**Comment by JedMeister** [comment] 2017-08-01 07:58
Hey @vondrt4, when you get a chance, could you please see if you can reproduce this issue now on the v14.2 build? If you can't I'd like to close it. Otherwise, we'll leave it open and re-pin it to v15.0.

**Comment by vondrt4** [comment] 2017-08-01 10:12
Just tried with your build for OpenStack. The problem is still there. I installed the image on our fast disk array and went trough the interactive initialization. Works fine after a reboot.

**Comment by JedMeister** [comment] 2017-08-02 05:10
Argh! Thanks for testing anyway. I'll pin it to v15.0 then and we'll have to have another look once we're on a Stretch base.

**Comment by JedMeister** [comment] 2018-10-16 01:27
I still haven't been able to reproduce this, so I'm closing for now. If you (or anyone else) can reproduce, then please reopen and/or open a new issue.

**Closed by JedMeister** 2018-10-16 01:27 UTC
Labels: bug, rails
