### ISSUE TITLE
jitterentropy-rngd in LXC container builds uses 100% CPU

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1636] opened 2021-08-05 01:59 UTC
[Viktor has posted in the forums](https://www.turnkeylinux.org/forum/support/wed-20210804-1030/wordpress-jitterentropy-rngd-100-cpu-usage) that `jitterentropy-rngd` is using 100% CPU in a LXC container running on latest v6 Proxmox.

I can't reproduce it myself, but I do have older Proxmox (so that probably explains it?).

Even though I can't reproduce, on a local LXC, I've tested disabling it and generating SSH keys and other 'randomness' heavy tasks. There seems to be no difference to the guest's entropy pool regardless of `jitterentropy-rngd` running or not! I can only assume that LXC gets entropy from the host?! (Which makes sense).

So whilst it does no harm on bare metal installs and is valuable in "proper" VMs, in LXC (and perhaps Docker?) builds, it appears to be irrelevant at best, deal breaker at worst!

Until we release updated builds, the workaround is to stop and disable it:

```
systemctl disable --now jitterentropy-rngd
```
Or alternatively, remove it altogether:
```
apt purge -y jitterentropy-rngd
```

**Comment by mooks42** [comment] 2021-09-20 20:03
I can confirm, this is also happening on proxmox 7.0-11 using turnkey mediaserver LXC.
Purging of course is "fixing" the problem, no issues so far.

**Comment by JedMeister** [comment] 2021-09-23 08:05
Thanks for reporting @mooks42. For whatever reason, even though I've finally updated to Proxmox v6.x I still can't reproduce it?! I wonder what the specific reason for that is? Perhaps it's some sort of kernel related thing? Anyway, we intend to remove the `jitterentropy-rngd` package from v17.x (based on Debian 11/Bullseye). We don't have an ETA on when that will be available, but soon I hope...

**Comment by casesolved-co-uk** [comment] 2021-12-08 18:50
Can confirm I also got this on Proxmox 7.1-4 with debian-10-turnkey-nginx-php-fastcgi_16.1-1
Just disabled it for now

**Comment by JedMeister** [comment] 2021-12-08 21:22
Thanks for confirming @casesolved-co-uk - as noted we intend to remove it for the LXC builds in our upcoming v17.x (Bullseye based) release. Best case it adds no value, worst case it causes this issue.

**Comment by nmiller0113** [comment] 2022-01-17 02:40
@JedMeister, this is interesting. I came across this when I was trying to figure out why I was having the same problem. I had only built one container on a brand new/fresh installed proxmox 7.1-8 instance at that time. Once I built another container, the CPU utilization from jitterentropy has dropped to nothing on the first one as well.

To rule out anything else I've removed the new containers I built and left only the one which was showing the 100% CPU with jitterentropy. I then restarted it multiple times and couldn't get the CPU to spike again.

To take it a step further, I shutdown the instance, rebooted proxmox, and restarted the single container and I was then able to reproduce the problem. I created a second container and right after it completed the turnkey install and updates the CPU dropped again on both. I then shut them both down and rebooted proxmox again and right when I started the two instances they CPU spiked on both.

This started to get me thinking that the actions happening on the containers was helping to generate the entropy on the host (following the host proxmox reboot) and allowing the CPU to drop more quickly...since it dropped right after the install and updates completed on the second instance. To test this theory further, with the two instances running both with CPU pegged at 100%, I built another container...but I hadn't run the install and updates yet...it was only built and turned on. All three containers were running with CPU at 100%, but that only lasted for a few mins. Then all three dropped, even before I ran the install and updates on the third/newest container. I think this is why you haven't seen it, as it requires the steps I mentioned to reproduce it and you've already likely reached entropy on your host (and not rebooted it). Just my thoughts though...I could be completely wrong :)

**Comment by nmiller0113** [comment] 2022-01-17 04:23
@JedMeister, well...I retract my previous statements. Strangely enough...the CPU dropped, but then after about an hour...all returned to where it was before with all 3 experiencing the pegged CPU. No clue now.

**Comment by JedMeister** [comment] 2022-01-17 04:25
@nmiller0113 - Wow! Thanks for doing the legwork to look into that. What you note sounds very likely!

FYI, my Proxmox was initially installed as v4.x and has been upgraded since then and has probably averaged a reboot every 6 months. I have ~10 TurnKey containers running. With what you've noted, it certainly is no surprise that I haven't seen this issue!

Still, my reading suggests that the actual value of jitterentropy-rngd in a LXC container is at best, zero.

**Comment by JedMeister** [comment] 2022-01-17 04:25
@nmiller0113 - Oops missed your latest post!

Ok, so that wasn't it after all...! My guess is that it's something else related to my Proxmox host...

**Comment by nmiller0113** [comment] 2022-01-17 04:27
@JedMeister must be something else then. I just ran apt update and apt full-upgrade on the third host and all the CPU's dropped back to 0% on the 3 containers. So I'll monitor and see how long it lasts :) I agree that the value is likely zero at best!

**Comment by nmiller0113** [comment] 2022-01-17 04:30
@JedMeister that's really strange, they all just jumped back to 100% minutes later...something is strange as I definitely had it down to normal on all hosts for at least a couple of hours previously...so something strange is going on. Not that it matters hugely as you're removing that from 17, but now I'm just curious haha

**Comment by nmiller0113** [comment] 2022-01-17 20:37
@JedMeister what I saw before must have been a fluke...or some strange behavior. I did some more research on this and it is definitely a [known issue that started at kernel 5.11](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=985302). It has been fixed in version 1.2.1-2 which is in the [package list for Debian 11](https://debian.pkgs.org/11/debian-main-amd64/jitterentropy-rngd_1.2.1-2_amd64.deb.html). I'm assuming that since v17 is buster that it would also use that version.  The current version running on your Debian 10 v16.1 release is 1.0.8-4 so it's quite old.

I'm only saying this since it may be beneficial to keep it in place in v17 for those that require entropy generation for a situation in which multiple crypto creation or other processes require use of a random number generator causing a depletion of the entropy pool.

Thanks again!

**Comment by JedMeister** [comment] 2022-01-18 03:54
@nmiller0113 - Hmm interesting. Thanks for following up!

It's still a bit weird that it works fine for me, but not others?!

Anyway, I was under the impression that as of circa 2020 (~v5.4?) the kernel can/will actively generate/collect entropy directly itself. But trying to find a source for that, it seems not so clear?! I did find a report about [kernel 5.4 actively collecting entropy](https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.4-Actively-Gen-Entropy) but I'm not completely convinced that it's doing exactly the same thing as jitterentropy-rngd.

So TBH, following your info, I'm nto 100% sure what to do. My inclination is still to remove it from the LXC build (only; and leave in other builds) as per the previous rationale that even in a best case, it's doing zero. But perhaps it's worth leaving in LXC too? 

It's such a shame that I can't reproduce it locally. If I could, then testing it would be super easy. Once we start working on v17.0 stable, perhaps I'll build a test LXC build and get people such as yourself to test it?! (Although we're probably still a little while away from that yet...).

**Comment by nmiller0113** [comment] 2022-01-18 21:37
@JedMeister, it's definitely a mystery why you're not seeing it, but then again I've not dug into what changes were made to correct the issue. I only know that it started in 5.11 but I'm guessing that there were some other specifics that weren't mentioned as to why it started at 5.11 and whether it impacted all platforms.

I'd be happy to test whenever you have v17 stable and an LXC build.

**Comment by xFABRIKA** [comment] 2022-01-22 18:25
hello @JedMeister and @nmiller0113 ,

I have a new fresh installation of proxmox 7.1-10 and just created a new CT with TurnKey 16.1-1...

same problem :( CPU 100% on a system that should be on idle :( 

I will try to purge the process, but what` jitterentropy-rngd i`s supposed to do? if I remove it will have have issues?

**Comment by nmiller0113** [comment] 2022-01-23 22:37
@xFABRIKA it is really only needed if you're doing anything very entropy-heavy. Since there hasn't been any report of problems following its purging, it's likely that the entropy operations already happening on the systems satisfy the needs of most and this service is just overkill and unnecessary. If you'd like to read more about what the service does, [this page](https://support.f5.com/csp/article/K74330414) explains it well. It's really more supplemental to the OS and not a required service.

**Comment by JedMeister** [comment] 2022-01-23 23:07
@xFABRIKA - @nmiller0113 is totally on the money and removing it from an LXC container will have no negative impact.

Although it's perhaps worth noting that `jitterentropy-rngd` is particularly valuable within a headless server as keyboard and mouse are significant sources of entropy. VMs (i.e. proper VMs, not containers) can also gain from an additional source of entropy.

**Comment by slantseto** [comment] 2022-03-18 16:26
Hello, I can also confirm also that jitterentropy-r uses full cpu at the two LXC Turnkey containers

**Closed** 2022-05-10 01:46 UTC
Labels: bug, core, docker (build type), buildtasks, container-lxc (build type)
