### ISSUE TITLE
On Odoo Description

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1303] opened 2019-02-19 14:22 UTC
It would be good to add the simple word "Python" or "Written in Python" to the Odoo Description or tags.  I just searched Python and found several Python Centric Turnkeylinux-Apps.  Odoo was not listed in the search returns  (was searching www.turnkeylinux.org).

**Comment by l-arnold** [comment] 2019-02-19 18:28
Separately but related:  

> I realize that the source is over in DocCyBlade, but I just did a search and found it a bit strange not to find a Odoo Repository under turnkeylinux-apps.

**Comment by JedMeister** [comment] 2019-02-20 22:36
FWIW the TurnKey appliance page for any particular appliance is generally `www.turnkey.linux.org/APPLIANCE-NAME`. E.g. in the case of Odoo: https://www.turnkeylinux.org/odoo

Appliance tags also have their own url (and I note that the Odoo appliance is already tagged with "python"). E.g.: https://www.turnkeylinux.org/python brings up Odoo as the 2nd listing.

Also, there is an appliance search box on the front page which will find Odoo straight up if you type "odoo" in the box. When I searched "python" in the search box, Odoo was the 2nd result.

The general (complete website) search box (top right corner on any page) is often less useful, but can sometime yield useful results. In the case of "odoo", "App" (i.e. type "odoo" in the box and select the "App" radio button) it's the only result. If you search "python", "App", it's less useful, although does appear at the top of the 2nd page.

Does that help?

Having said all that, I take onboard your comment and will look to specifically add a note to the appliance page that Odoo is written in Python. If you have any specific suggestion, please feel free to have a look at the [readme in the buildcode](https://github.com/turnkeylinux-apps/odoo/blob/master/README.rst). The appliance pages on the website are generated from the text of the readme.

**Comment by JedMeister** [comment] 2019-02-20 22:56
Oops, missed this bit:

>Separately but related:
>
>> I realize that the source is over in DocCyBlade, but I just did a search and found it a bit strange not to find a Odoo Repository under turnkeylinux-apps.

It's here: https://github.com/turnkeylinux-apps/odoo

**Comment by l-arnold** [comment] 2019-02-20 23:12
What I was referring to:

1st:
If you are in TurnkeyApps:
https://www.turnkeylinux.org/all

Search "Python" .  Odoo does not show up.

2nd:
In https://github.com/turnkeylinux-apps 
 I was not finding Odoo as an App.

**Comment by l-arnold** [comment] 2019-02-20 23:16
I do find it if I explicitly look for it.  When I was scrolling through turnkeylinux-apps I was not finding it yesterday.
I take it all back on that subject. (unless I can repeat somehow)

**Comment by JedMeister** [comment] 2019-02-20 23:27
I'm going to reopen this as it could do with some improvement. I suspect that part of the issue is that so much of our code is written in python, but conversely, the Odoo appliance readme (and therefore the appliance page text) doesn't explicitly note that Odd is a "python app". If we update the readme to explicitly mention python, then I think that will improve the situation.

> 1st:
If you are in TurnkeyApps:
https://www.turnkeylinux.org/all
>
> Search "Python" . Odoo does not show up.

Yes, I see your point. It certainly doesn't come up searching from that angle for me either (not even on the second page as I expected it to).

> 2nd:
In https://github.com/turnkeylinux-apps
I was not finding Odoo as an App.

It comes up if I search for "odoo", but not if I search for "python", so again you raise a valid point IMO.

**Comment by JedMeister** [comment] 2019-03-22 00:04
closed by https://github.com/turnkeylinux-apps/odoo/commit/fc3c8913d6d360f52038a1c644697b0c5d169896

I still need to update the website, but I'll do that when I publish the updates (should be next week).

**Closed by JedMeister** 2019-03-22 00:04 UTC
Labels: feature, odoo, website
