### ISSUE TITLE
Xen build: Drupal7 - mysql does not start

### ISSUE THREAD

**Issue by DirkDeWachter** [turnkeylinux/tracker#643] opened 2016-05-18 11:17 UTC
Hi,
I tested the XEN-image for the drupal7 server. Initialization did not succeed due to the mysql not starting. After researching the internet, I found that changing the ownership of /var/lib/mysql (by chmod -R mysql.mysql /var/lib/mysql) solved this issue.

Dirk

**Comment by vondrt4** [comment] 2016-05-18 11:30
Hi,
I've got Drupal7 on OpenStack, build May 6, 2016, 9:22 a.m., and it works OK.

**Comment by JedMeister** [comment] 2016-05-19 05:01
I can't reproduce this either... I tested ISO and container builds. 

I don't have access to a Xen server so can't test that but there shouldn't be anything Xen specific that should break MySQL... 

However, I expect that it was something to do with the way that you extracted the tar archive when setting it up for use in Xen (i.e. changed permissions on files which upset MySQL). I say that because by default the directory you refer to is already owned by `mysql`! This is from the LAMP appliance (which is what the Drupal7 appliance is built on):
````
root@lamp-14 ~# ls -l /var/lib/mysql
total 28688
-rw-r--r--  1 mysql mysql        0 Apr 27 10:18 debian-5.5.flag
-rw-rw----  1 mysql mysql  5242880 May 19 04:57 ib_logfile0
-rw-rw----  1 mysql mysql  5242880 Apr  8 09:47 ib_logfile1
-rw-rw----  1 mysql mysql 18874368 May 16 13:06 ibdata1
drwx------+ 2 mysql mysql     4096 May 17 06:27 lychee
drwx------+ 2 mysql mysql     4096 May 13 06:27 mysql
-rw-------  1 mysql mysql        6 Apr 27 10:18 mysql_upgrade_info
drwx------+ 2 mysql mysql     4096 Apr 27 10:18 performance_schema
````

So I'm shutting this for now.

**Comment by DirkDeWachter** [comment] 2016-05-26 18:09
Hi Jeremy,

I looked into this.
When I list the tarfile (tar jtvf turnkey-drupal7-14.1-jessie-amd64-xen.tar.bz2), I get this for /var/lib/mysql:
               drwx------ ntp/netdev                 0 2016-04-08 11:37 ./var/lib/mysql
               As you can see the owner is not recorded as mysql/mysql

When I dump it numerically (tar –numeric-owner  jtvf turnkey-drupal7-14.1-jessie-amd64-xen.tar.bz2), we can see the numeric ids:
               drwx------ 104/107                    0 2016-04-08 11:37 ./var/lib/mysql
               And in ./etc/passwd, ./etc/group
                              mysql:x:104:107:MySQL Server,,,:nonexistent:/bin/false
                              mysql :x :107

So, numerically the id’s are correct in the tarfile, but the names are not.

When I use the first variant of tar to extract, the directory gets the ntp/netdev owner (with different id’s on my debian Jessie system where I do the extraction).
When I use the second variant, the directory gets indeed as owners 104/107, but as far as I know it is not documented that this option should be used.

As you may state that I didn’t do the extraction correctly, I may as well pose that the tar-file is not well packed (having different owner/group names that are non-consistent with the passwd and group files in the same tar). Maybe this happened because two tarfiles from the LAMP appliance was merged with the drupal-tar and both were created on different systems?

So, I hope sincerely that this issue is either corrected or documented for future users.

Many thanks,

Dirk

Van: Jeremy Davis [mailto:notifications@github.com]
Verzonden: donderdag 19 mei 2016 7:02
Aan: turnkeylinux/tracker <tracker@noreply.github.com>
CC: De Wachter, Dirk <dirk.dewachter@zorg-en-gezondheid.be>; Author <author@noreply.github.com>
Onderwerp: Re: [turnkeylinux/tracker] Drupal7: mysql does not start (#643)


I can't reproduce this either... I tested ISO and container builds.

I don't have access to a Xen server so can't test that but there shouldn't be anything Xen specific that should break MySQL...

However, I expect that it was something to do with the way that you extracted the tar archive when setting it up for use in Xen (i.e. changed permissions on files which upset MySQL). I say that because by default the directory you refer to is already owned by mysql! This is from the LAMP appliance (which is what the Drupal7 appliance is built on):

root@lamp-14 ~# ls -l /var/lib/mysql

total 28688

-rw-r--r--  1 mysql mysql        0 Apr 27 10:18 debian-5.5.flag

-rw-rw----  1 mysql mysql  5242880 May 19 04:57 ib_logfile0

-rw-rw----  1 mysql mysql  5242880 Apr  8 09:47 ib_logfile1

-rw-rw----  1 mysql mysql 18874368 May 16 13:06 ibdata1

drwx------+ 2 mysql mysql     4096 May 17 06:27 lychee

drwx------+ 2 mysql mysql     4096 May 13 06:27 mysql

-rw-------  1 mysql mysql        6 Apr 27 10:18 mysql_upgrade_info

drwx------+ 2 mysql mysql     4096 Apr 27 10:18 performance_schema

So I'm shutting this for now.

**Comment by JedMeister** [comment] 2016-05-30 06:00
We build all our images on a clean TKLDev of the same major version (i.e. v14.0 was built on TKLDev v14.0; v14.1 was also built on v14.0 TKLDev). So the OS shouldn't play any factor.

Regardless, thanks for the further input @DirkDeWachter 

I'll reopen this issue and we'll look into it further and as you say, either resolve the issue (if there is one) or document it better if we can't find one.

**Comment by JedMeister** [comment] 2021-02-11 04:55
We have had no further reports of this issue and I've been unable to reproduce it, so I'm going to close it.

**Closed by JedMeister** 2021-02-11 04:55 UTC
Labels: bug, drupal7, xen (build type)
