### ISSUE TITLE
Wordpress installation failed

### ISSUE THREAD

**Issue by BenasPaulikas** [turnkeylinux/tracker#1737] opened 2022-06-12 09:33 UTC
Hey there.

I'm using Proxmox and they are offering debian-10-turnkey-wordpress_16.1-1_amd64.tar.gz

After installing it's failing to start apache2 (for example:)

```
root@vps870577 ~# service apache2 status
* apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2022-06-12 09:31:15 UTC; 3s ago
     Docs: https://httpd.apache.org/docs/2.4/
  Process: 16791 ExecStart=/usr/sbin/apachectl start (code=exited, status=226/NAMESPACE)

Jun 12 09:31:15 vps870577 systemd[1]: Starting The Apache HTTP Server...
Jun 12 09:31:15 vps870577 systemd[16791]: apache2.service: Failed to set up mount namespacing: Permission denied
Jun 12 09:31:15 vps870577 systemd[16791]: apache2.service: Failed at step NAMESPACE spawning /usr/sbin/apachectl: Permission denied
Jun 12 09:31:15 vps870577 systemd[1]: apache2.service: Control process exited, code=exited, status=226/NAMESPACE
Jun 12 09:31:15 vps870577 systemd[1]: apache2.service: Failed with result 'exit-code'.
Jun 12 09:31:15 vps870577 systemd[1]: Failed to start The Apache HTTP Server.

```
Is this expected ? Am I doing something wrong ?

**Comment by JedMeister** [comment] 2022-06-14 03:09
FWIW for support queries, ideally we prefer use of our [forums](https://www.turnkeylinux.org/forum) (and reserve "GitHub issues" for confirmed bugs and/or feature requests).

But seeing as you're already here...:

It looks like you are trying to run it as a privileged container!? By default it needs to run as unprivileged. If run unpriveledged it should "just work". If you really want to run it privileged (not recommended) then you'll need to modify the service files so that Apache (and possibly others) will run. I forget the specifics but IIRC there are a few posts on the Proxmox forums that explain the required steps.

I'll close this now, but feel free to post back if need be.

**Closed by JedMeister** 2022-06-14 03:09 UTC

**Comment by BenasPaulikas** [comment] 2022-06-15 20:07
@JedMeister ty for reply. I really appreciate your effort. All good now.
