### ISSUE TITLE
CouchDB Applance: Unable to create database with "/" in name

### ISSUE THREAD

**Issue by zinthose** [turnkeylinux/tracker#629] opened 2016-05-05 20:07 UTC
I'm attempting to create a database named "artist/guid".
With futon I'm using the UI to with name "artist/guid" returns: "no_db_file"
With the HTTP API I used:
curl -vX put http://127.0.0.1:5984/artist%2Fguid/
returns: "no_db_file"
I enabled debug logging and this is the error the log produces.

```
Could not open file /usr/local/var/lib/couchdb/artist/guid.couch: no such file or directory
```

I checked the path and on a whim created the "artist" directory using the couchdb account, which is the execution context of the server. No change.
This feels like a permission issue within the OS but I'm not sure what I'm missing. Any ideas?

I have an open ticket with CouchDB as on this issue at:
https://issues.apache.org/jira/browse/COUCHDB-3011

**Comment by JedMeister** [comment] 2016-05-06 04:56
Hey. 

TBH my knowledge of CouchDB extends to the little bit of work that I did on the appliance so I'm far from an expert. On face value I would assume that a DB name with a slash in it would be a bad thing; but a quick bit of googling confirms that it is legit and furthermore that you're doing it right... So from what I can gather it should indeed work.

WRT to permissions, I'm not so sure as judging from your comment it seems that you created the directory using the CouchDB user account so it should have full access. My only other suggestion is that perhaps there is some config that isn't ideal, or as it should be by default in our appliance. I hope not, but it's possible. Please post back if you have any progress. Also I'll try to have a little fiddle myself if I get a chance (not that it will probably be much help but perhaps?)

Regardless thanks fpr posting and also following up with upstream! :smile:

**Comment by JedMeister** [comment] 2016-05-06 05:35
PS if you're at all interested the build code for the CouchDB appliance is here on GitHUb:
https://github.com/turnkeylinux-apps/couchdb

Probably the relevant config bit is the main config script conf.d/main: https://github.com/turnkeylinux-apps/couchdb/blob/master/conf.d/main

Note that `/etc/couchdb` is a symlink to /usr/local/etc/couchdb 

Also it may be worth checking the CounchDB logs: `/usr/local/var/log/couchdb`

**Comment by JedMeister** [comment] 2016-05-06 05:54
I think I've worked it out... (Assuming that I'm right) you were sort of on the right track... It's an authentication issue. You need to supply the username & password! E.g. I just did this:
````
root@couchdb ~# curl -X PUT http://admin:Passw0rd@127.0.0.1:5984/artist%2Fguid/
{"ok":true}
````
And now I have a `artist/guid` DB! 
````
root@couchdb ~# curl -X GET http://127.0.0.1:5984/_all_dbs
["_replicator","_users","artist/guid","tklwebcp"]
````
:smile:

**Comment by JedMeister** [comment] 2016-05-06 06:16
I've updated the README (and the corresponding appliance page) to note that "admin party" is disabled and authentication is enabled:
https://github.com/turnkeylinux-apps/couchdb/commit/d69ec61203c844c81a1e4799d7ed6aff6446afa9
https://www.turnkeylinux.org/couchdb

I'm going to close this now, but feel free to reopen if you still have concerns (or open a new issue if you find something else that doesn't work).

**Comment by zinthose** [comment] 2016-05-06 14:52
Currently traveling but will try your solution when I get back.  The only
continuing concern is how it continues to fail when using the futon UI when
logged in as the admin.  This maybe an issue with Futon.  It also fails to
replicate from a normal db to one with a "/".

I'll tinker with it tonight.

Regards,
Dane Jones

*Sent from Android Phone*

Closed #629 <https://github.com/turnkeylinux/tracker/issues/629>.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/turnkeylinux/tracker/issues/629#event-652289140>

**Comment by zinthose** [comment] 2016-05-07 19:10
I checked your findings and it dose indeed work from curl.  An oops on my part was also discovered thanks to your efforts.  I was using "put" and not "PUT"  gotta love case sensitivity.

However, futon still doesn't work and it returns the no_db_file when logged in as the administrator.  Not sure if this is a configuration issue or an issue with Futon itself.

**Comment by zinthose** [comment] 2016-05-08 03:17
Upon closer inspection.. Even though the database says it is created, if you try and access the database in futon and I find the guid.couch file is not in the artist folder.

**Comment by JedMeister** [comment] 2016-05-09 10:07
Apologies on delayed response. I can confirm that futon does not seem to deal with db names with slashes in them. Even the one that i made with curl doesn't actually work that great. We'll have to look into this a little more... I wonder if it is something to do with the Nginx proxying that the appliance uses?

**Comment by JedMeister** [comment] 2016-05-09 11:24
It seems to be an issue with the nginx proxy config. If you reconfigure couchDB to connect directly (i.e. set `bind_address 0.0.0.0` in `/etc/couchdb/default.ini`) the path with a slash works fine.

**Comment by JedMeister** [comment] 2016-05-09 15:21
I've discovered what the issue is but can't for the life of me resolve it properly... :frowning: 

It is caused by the rewrite rule that provides the example app; which is basically the landing page. If you have no need for the example app then you can safely disable the rewrite rule. 

However if you use COuchDB to host your app and proxy it with Nginx then you'll possibly end up with the same issue in the end anyway; although I guess once you get to that point you probably won't need to admin page (`_utils`) anyway.

So to disable the rewrite rule do this:
````
sed -i "s|rewrite|#rewrite|" /etc/nginx/include/couchdb-proxy
service nginx restart
````
To re-enable it:
````
sed -i "s|#rewrite|rewrite|" /etc/nginx/include/couchdb-proxy
service nginx restart
````

**Comment by JedMeister** [comment] 2016-05-09 15:22
PS I'm going to leave this issue open for now as perhaps there is a proper fix (that I just couldn't work out...)

**Comment by zinthose** [comment] 2016-05-09 16:43
Interesting, I'm green to Nginx and I'm just now looking it over.  I did find an article online about configuring CouchDB for Nginx it's all mumbo jumbo to me atm but maybe it would provide some insight for you: 
https://cwiki.apache.org/confluence/display/COUCHDB/Nginx+as+a+proxy

On a different note, I installed nodejs and Fauxton to assist me with development.  Fauxton is the eventual replacement for Futon but is currently still in development.  It's working just fine but that's probably because it is running independently and not through Nginx.

**Comment by JedMeister** [comment] 2016-05-09 23:58
Thanks for that. I actually came across that page last night when I was tinkering. However, I noticed that right down the bottom is some stuff that I hadn't tried (it provides slightly different config between http and https) so perhaps that's worth further investigation?

Thanks too for the additional info re Fauxton. I had never heard of it. Is it a Nodejs app? Or did you add that for other reasons?

**Comment by zinthose** [comment] 2016-05-10 00:10
Again I'm green to Nginx so I'm not the best to answer that myself.
Fauxton is indeed a nodejs app.

**Comment by smcatala** [comment] 2016-09-06 20:06
removing the trailing slash on line 13 of `/etc/nginx/include/couchdb-proxy` does the trick.

**Comment by JedMeister** [comment] 2016-09-11 22:55
Thanks @smcatala! Awesome! :smile:

**Closed** 2017-07-09 22:25 UTC
Labels: bug, couchdb, workaround
