### ISSUE TITLE
OpenStack build of 15.x - inithooks are not run

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#1340] opened 2019-07-03 16:38 UTC
Sorry that I didn't see this sooner, but the OpenStack builds of all the 15.x series are missing the symlink
/etc/systemd/system/basic.target.wants/inithooks-openstack.service
meaning that inithooks are not run on start and the instance is not accessible. Will you be able to rebuild them?

**Comment by JedMeister** [comment] 2019-07-03 23:01
Hi @vondrt4 - Oops! :cry: 

That was an oversight on my behalf... Thanks for picking it up (better late than never!).

I assume that simply adding a `systemctl enable inithooks-openstack.service` to the [relevant conf script](https://github.com/turnkeylinux/buildtasks/blob/master/patches/openstack/conf) should do the trick...?! Plus we'll need to `touch /var/lib/turnkey-info/inithooks.service/openstack` (as required by the [unit file](/var/lib/turnkey-info/inithooks.service/openstack)).

Should I do a test build first to confirm? Or just rebuild?

**Comment by JedMeister** [comment] 2019-07-03 23:14
Hang on, actually, the `inithooks-openstack.service` file is already being included by default via the install of the [Inithooks package](https://github.com/turnkeylinux/inithooks) ([here](https://github.com/turnkeylinux/inithooks/blob/master/debian/inithooks-openstack.service) it is!).

However, it's not being enabled by default as the [others are](https://github.com/turnkeylinux/inithooks/blob/master/debian/rules#L7-L9).

Generation of the `/var/lib/turnkey-info/inithooks.service/openstack` is already being handled by [buildtasks/bin/build-tag](https://github.com/turnkeylinux/buildtasks/blob/master/bin/build-tag).

So the "proper" fix is in the inithooks package, but the easiest fix for now would be to enable the `inithooks-openstack.service` in buildtasks as I noted initially.

@vondrt4 - Could you please just double check that the `/var/lib/turnkey-info/inithooks.service/openstack` file exists and all that's missing is the symlink and I'll just rebuild.

**Comment by vondrt4** [comment] 2019-07-04 07:26
Yes, my fix was to manually create the symlink. If "systemctl enable" puts it in the same place, then it's the cleaner way to do it.

**Comment by JedMeister** [comment] 2019-07-05 05:32
Ok great thanks. I'll aim to take care of this early next week. Thanks again for the heads up.

**Comment by vondrt4** [comment] 2019-07-22 11:02
Hi! any news on this?

**Comment by JedMeister** [comment] 2019-07-26 02:03
Hi @vondrt4 - Apologies on delays with this, plus my slow response to your question. I've been tied up with other stuff (working on v16.0) but will make this a priority for early next week. If I can get it done Monday (which seems possible) then they should be published by mid-late next week.

**Comment by JedMeister** [comment] 2019-08-07 23:45
Hi @vondrt4 - Apologies on the delay with this one. I was having some issues with the Openstack builds failing. I couldn't reproduce the issue locally, only on our build infrastructure so it took a bit longer than anticipated to troubleshoot and resolve.

Anyway, all OpenStack builds have been rebuilt with the fix included. I also updated 2 specific appliances at the same time (Moodle and GitLab). Other than those 2, there is no version bump for the fixed images, they've just been rebuilt (if you look on the mirror, the "creation date" should be late July/early August). FYI I've attached a list of the rebuilt/current appliances versions that should all have working OpenStack builds now.

[2019-09-02-mirror.list.txt](https://github.com/turnkeylinux/tracker/files/3479255/2019-09-02-mirror.list.txt)

Closing for now, but please do not hesitate to let me know if you have any further concerns or issues and I'll do my best to resolve ASAP.

**Closed by JedMeister** 2019-08-07 23:45 UTC
Labels: bug, buildtasks, openstack (build type)

**Comment by l-arnold** [comment] 2019-08-08 05:57
I will do some testing withe this Jeremy.  Thank you for your efforts. 
 Landis
